// FILE: geom_surface_extensions.rs
//! Surface extension stubs modelled after `Geom_RectangularTrimmedSurface` and
//! `Geom_SweptSurface` from OpenCASCADE Technology (TKG3d).
//!
//! Three types are provided:
//!
//! - [`TrimmedSurface`]  — named basis surface trimmed to a rectangular
//!   `[u1, u2] × [v1, v2]` parametric domain.
//!   (`Geom_RectangularTrimmedSurface`)
//!
//! - [`SweptSurface`]    — a surface formed by sweeping a named profile curve
//!   along a named spine curve.
//!   (`Geom_SweptSurface`)
//!
//! - [`ExtrusionSurface`] — a surface formed by extruding a polyline profile
//!   along a constant direction vector.
//!   (`Geom_SurfaceOfLinearExtrusion`)
//!
//! All types use only `std`. No external crates are referenced.

// ─────────────────────────── TrimmedSurface ─────────────────────────────────

/// A named basis surface trimmed to the rectangular parametric domain
/// `[u1, u2] × [v1, v2]`.
///
/// `basis` is a label identifying the underlying surface (e.g. a plane,
/// cylinder, or B-spline surface name). The parametric bounds are stored
/// so that evaluation can clamp or report the active domain.
///
/// Mirrors the interface of `Geom_RectangularTrimmedSurface`.
// occt-ref: Geom_RectangularTrimmedSurface
pub struct TrimmedSurface {
    /// Name / identifier of the basis surface being trimmed.
    pub basis: String,
    /// Lower U parameter bound.
    pub u1: f64,
    /// Upper U parameter bound.
    pub u2: f64,
    /// Lower V parameter bound.
    pub v1: f64,
    /// Upper V parameter bound.
    pub v2: f64,
}

impl TrimmedSurface {
    /// Construct a new trimmed surface.
    ///
    /// Parameter bounds are normalised so that `u1 <= u2` and `v1 <= v2`
    /// regardless of the order supplied by the caller (mirrors OCCT's
    /// `Geom_RectangularTrimmedSurface` constructor behaviour).
    pub fn new(basis: &str, u1: f64, u2: f64, v1: f64, v2: f64) -> Self {
        let (u1, u2) = if u1 <= u2 { (u1, u2) } else { (u2, u1) };
        let (v1, v2) = if v1 <= v2 { (v1, v2) } else { (v2, v1) };
        Self {
            basis: basis.to_owned(),
            u1,
            u2,
            v1,
            v2,
        }
    }

    /// Evaluate a point on the trimmed surface at parameters `(u, v)`.
    ///
    /// The stub implementation clamps `u` to `[u1, u2]` and `v` to
    /// `[v1, v2]`, then returns the point `(u_clamped, v_clamped, 0.0)`,
    /// which corresponds to evaluation on the canonical XY plane.  A real
    /// implementation would dispatch to the named basis surface.
    pub fn evaluate(&self, u: f64, v: f64) -> [f64; 3] {
        let uc = u.clamp(self.u1, self.u2);
        let vc = v.clamp(self.v1, self.v2);
        [uc, vc, 0.0]
    }

    /// Return `true` when the surface is closed (periodic) in the U direction.
    ///
    /// For this stub the surface is considered U-closed when the U span
    /// covers a full period of 2π, consistent with OCCT's convention for
    /// revolution surfaces.
    pub fn is_u_closed(&self) -> bool {
        (self.u2 - self.u1 - std::f64::consts::TAU).abs() < 1e-10
    }

    /// Return `true` when the surface is closed (periodic) in the V direction.
    ///
    /// Same 2π heuristic applied to the V span.
    pub fn is_v_closed(&self) -> bool {
        (self.v2 - self.v1 - std::f64::consts::TAU).abs() < 1e-10
    }
}

// ─────────────────────────── SweptSurface ───────────────────────────────────

/// A surface generated by sweeping a profile curve along a spine curve.
///
/// Both `profile` and `spine` are string identifiers that refer to named
/// curves defined elsewhere in the model.  The struct acts as a lightweight
/// descriptor / handle, matching the abstract base class role played by
/// `Geom_SweptSurface` in OCCT (which stores the basis curve and sweep
/// direction but defers concrete evaluation to its subclasses).
// occt-ref: Geom_SweptSurface
pub struct SweptSurface {
    /// Name / identifier of the profile curve (the cross-section being swept).
    pub profile: String,
    /// Name / identifier of the spine curve (the path of the sweep).
    pub spine: String,
}

impl SweptSurface {
    /// Construct a new swept surface descriptor.
    pub fn new(profile: &str, spine: &str) -> Self {
        Self {
            profile: profile.to_owned(),
            spine: spine.to_owned(),
        }
    }

    /// Evaluate a point on the swept surface at parameters `(u, v)`.
    ///
    /// `u` parameterises position along the spine and `v` parameterises the
    /// cross-section profile at that spine location.  The stub returns
    /// `(u, v, 0.0)` as a placeholder; a full implementation would look up
    /// the profile and spine curves by name and compute the actual swept
    /// point.
    pub fn evaluate(&self, u: f64, v: f64) -> [f64; 3] {
        // Stub: identity mapping onto the XY plane.
        [u, v, 0.0]
    }
}

// ─────────────────────────── ExtrusionSurface ───────────────────────────────

/// A surface of linear extrusion: a polyline profile swept along a constant
/// direction vector.
///
/// The surface is parameterised as:
/// ```text
/// P(u, v) = C(u) + v * direction
/// ```
/// where `C(u)` is a point on the polyline profile interpolated by the
/// normalised arc-length parameter `u ∈ [0, 1]`, and `v` is the sweep
/// distance along `direction`.
///
/// Mirrors `Geom_SurfaceOfLinearExtrusion`.
// occt-ref: Geom_SweptSurface
pub struct ExtrusionSurface {
    /// The profile polyline as an ordered sequence of 3-D points.
    pub profile: Vec<[f64; 3]>,
    /// The extrusion direction vector (need not be unit length on construction;
    /// `evaluate` normalises it internally).
    pub direction: [f64; 3],
}

impl ExtrusionSurface {
    /// Construct a new extrusion surface with an empty profile and the given
    /// extrusion direction.
    pub fn new(dir: [f64; 3]) -> Self {
        Self {
            profile: Vec::new(),
            direction: dir,
        }
    }

    /// Append a point to the profile polyline.
    pub fn add_profile_pt(&mut self, p: [f64; 3]) {
        self.profile.push(p);
    }

    /// Evaluate a point on the extrusion surface at parameters `(u, v)`.
    ///
    /// `u` is a normalised arc-length parameter over the profile polyline
    /// (`0.0` → first point, `1.0` → last point).  Linear interpolation is
    /// used between adjacent profile points.  `v` is the sweep distance along
    /// the (normalised) extrusion direction.
    ///
    /// Returns `[0.0, 0.0, 0.0]` when the profile contains fewer than two
    /// points, or when the total arc-length of the profile is zero.
    pub fn evaluate(&self, u: f64, v: f64) -> [f64; 3] {
        let n = self.profile.len();
        if n == 0 {
            return [0.0, 0.0, 0.0];
        }
        if n == 1 {
            // Single point: no arc to interpolate; extrude that point.
            let p = self.profile[0];
            let d = unit_vec(self.direction);
            return [p[0] + v * d[0], p[1] + v * d[1], p[2] + v * d[2]];
        }

        // Compute cumulative arc lengths.
        let mut arc: Vec<f64> = Vec::with_capacity(n);
        arc.push(0.0);
        for i in 1..n {
            let seg = seg_len(self.profile[i - 1], self.profile[i]);
            arc.push(arc[i - 1] + seg);
        }
        let total = arc[n - 1];
        if total == 0.0 {
            // Degenerate profile: all points coincident.
            let p = self.profile[0];
            let d = unit_vec(self.direction);
            return [p[0] + v * d[0], p[1] + v * d[1], p[2] + v * d[2]];
        }

        // Map u ∈ [0, 1] to target arc length.
        let u_clamped = u.clamp(0.0, 1.0);
        let target = u_clamped * total;

        // Find the segment containing `target`.
        let mut seg_idx = n - 2; // default: last segment
        for i in 0..n - 1 {
            if arc[i + 1] >= target {
                seg_idx = i;
                break;
            }
        }

        // Interpolate within the segment.
        let seg_start = arc[seg_idx];
        let seg_end = arc[seg_idx + 1];
        let t = if (seg_end - seg_start).abs() < f64::EPSILON {
            0.0
        } else {
            (target - seg_start) / (seg_end - seg_start)
        };

        let a = self.profile[seg_idx];
        let b = self.profile[seg_idx + 1];
        let cx = a[0] + t * (b[0] - a[0]);
        let cy = a[1] + t * (b[1] - a[1]);
        let cz = a[2] + t * (b[2] - a[2]);

        // Add the linear sweep offset.
        let d = unit_vec(self.direction);
        [cx + v * d[0], cy + v * d[1], cz + v * d[2]]
    }
}

// ─────────────────────────── internal helpers ────────────────────────────────

/// Return the Euclidean length of a polyline segment.
#[inline]
fn seg_len(a: [f64; 3], b: [f64; 3]) -> f64 {
    let dx = b[0] - a[0];
    let dy = b[1] - a[1];
    let dz = b[2] - a[2];
    (dx * dx + dy * dy + dz * dz).sqrt()
}

/// Normalise a direction vector.  Returns `[0.0, 0.0, 1.0]` for a zero vector
/// (fallback to +Z, matching OCCT's degenerate-direction convention).
#[inline]
fn unit_vec(v: [f64; 3]) -> [f64; 3] {
    let len = (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]).sqrt();
    if len < f64::EPSILON {
        [0.0, 0.0, 1.0]
    } else {
        [v[0] / len, v[1] / len, v[2] / len]
    }
}

// ─────────────────────────────── unit tests ──────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::f64::consts::TAU;

    // ── TrimmedSurface ────────────────────────────────────────────────────────

    #[test]
    fn trimmed_surface_new_normalises_bounds() {
        let s = TrimmedSurface::new("plane", 2.0, -1.0, 5.0, 3.0);
        assert_eq!(s.u1, -1.0);
        assert_eq!(s.u2, 2.0);
        assert_eq!(s.v1, 3.0);
        assert_eq!(s.v2, 5.0);
    }

    #[test]
    fn trimmed_surface_stores_basis_name() {
        let s = TrimmedSurface::new("cylinder_1", 0.0, TAU, -5.0, 5.0);
        assert_eq!(s.basis, "cylinder_1");
    }

    #[test]
    fn trimmed_surface_evaluate_clamps_u() {
        let s = TrimmedSurface::new("plane", 0.0, 1.0, 0.0, 1.0);
        let p = s.evaluate(3.0, 0.5);
        assert!((p[0] - 1.0).abs() < 1e-14, "u should be clamped to u2=1.0, got {}", p[0]);
        assert!((p[1] - 0.5).abs() < 1e-14);
        assert!(p[2].abs() < 1e-14);
    }

    #[test]
    fn trimmed_surface_evaluate_clamps_v() {
        let s = TrimmedSurface::new("plane", 0.0, 1.0, 0.0, 1.0);
        let p = s.evaluate(0.5, -2.0);
        assert!((p[1] - 0.0).abs() < 1e-14, "v should be clamped to v1=0.0, got {}", p[1]);
    }

    #[test]
    fn trimmed_surface_evaluate_interior() {
        let s = TrimmedSurface::new("plane", -10.0, 10.0, -10.0, 10.0);
        let p = s.evaluate(3.5, -2.7);
        assert!((p[0] - 3.5).abs() < 1e-14);
        assert!((p[1] - (-2.7)).abs() < 1e-14);
    }

    #[test]
    fn trimmed_surface_is_u_closed_true() {
        let s = TrimmedSurface::new("sphere", 0.0, TAU, 0.0, 1.0);
        assert!(s.is_u_closed());
    }

    #[test]
    fn trimmed_surface_is_u_closed_false() {
        let s = TrimmedSurface::new("plane", 0.0, 1.0, 0.0, 1.0);
        assert!(!s.is_u_closed());
    }

    #[test]
    fn trimmed_surface_is_v_closed_true() {
        let s = TrimmedSurface::new("torus", 0.0, 1.0, 0.0, TAU);
        assert!(s.is_v_closed());
    }

    #[test]
    fn trimmed_surface_is_v_closed_false() {
        let s = TrimmedSurface::new("plane", 0.0, 1.0, 0.0, 1.0);
        assert!(!s.is_v_closed());
    }

    // ── SweptSurface ──────────────────────────────────────────────────────────

    #[test]
    fn swept_surface_stores_names() {
        let s = SweptSurface::new("circle_profile", "helix_spine");
        assert_eq!(s.profile, "circle_profile");
        assert_eq!(s.spine, "helix_spine");
    }

    #[test]
    fn swept_surface_evaluate_identity_stub() {
        let s = SweptSurface::new("prof", "sp");
        let p = s.evaluate(1.5, 2.5);
        assert!((p[0] - 1.5).abs() < 1e-14);
        assert!((p[1] - 2.5).abs() < 1e-14);
        assert!(p[2].abs() < 1e-14);
    }

    // ── ExtrusionSurface ──────────────────────────────────────────────────────

    #[test]
    fn extrusion_surface_empty_profile_returns_origin() {
        let s = ExtrusionSurface::new([0.0, 0.0, 1.0]);
        let p = s.evaluate(0.5, 3.0);
        assert_eq!(p, [0.0, 0.0, 0.0]);
    }

    #[test]
    fn extrusion_surface_single_point_extrudes() {
        let mut s = ExtrusionSurface::new([0.0, 0.0, 1.0]);
        s.add_profile_pt([1.0, 2.0, 0.0]);
        let p = s.evaluate(0.0, 5.0);
        assert!((p[0] - 1.0).abs() < 1e-12);
        assert!((p[1] - 2.0).abs() < 1e-12);
        assert!((p[2] - 5.0).abs() < 1e-12);
    }

    #[test]
    fn extrusion_surface_two_points_u_start() {
        let mut s = ExtrusionSurface::new([0.0, 0.0, 1.0]);
        s.add_profile_pt([0.0, 0.0, 0.0]);
        s.add_profile_pt([4.0, 0.0, 0.0]);
        // u=0.0 -> first profile point (0,0,0), v=2 -> (0,0,2)
        let p = s.evaluate(0.0, 2.0);
        assert!((p[0] - 0.0).abs() < 1e-12);
        assert!((p[1] - 0.0).abs() < 1e-12);
        assert!((p[2] - 2.0).abs() < 1e-12);
    }

    #[test]
    fn extrusion_surface_two_points_u_end() {
        let mut s = ExtrusionSurface::new([0.0, 0.0, 1.0]);
        s.add_profile_pt([0.0, 0.0, 0.0]);
        s.add_profile_pt([4.0, 0.0, 0.0]);
        // u=1.0 -> last profile point (4,0,0), v=3 -> (4,0,3)
        let p = s.evaluate(1.0, 3.0);
        assert!((p[0] - 4.0).abs() < 1e-12, "x={}", p[0]);
        assert!((p[1] - 0.0).abs() < 1e-12);
        assert!((p[2] - 3.0).abs() < 1e-12, "z={}", p[2]);
    }

    #[test]
    fn extrusion_surface_two_points_u_mid() {
        let mut s = ExtrusionSurface::new([0.0, 0.0, 1.0]);
        s.add_profile_pt([0.0, 0.0, 0.0]);
        s.add_profile_pt([4.0, 0.0, 0.0]);
        // u=0.5 -> midpoint (2,0,0), v=0 -> (2,0,0)
        let p = s.evaluate(0.5, 0.0);
        assert!((p[0] - 2.0).abs() < 1e-12, "x={}", p[0]);
    }

    #[test]
    fn extrusion_surface_direction_normalised() {
        // Direction (0,0,2) should be normalised to (0,0,1).
        let mut s = ExtrusionSurface::new([0.0, 0.0, 2.0]);
        s.add_profile_pt([0.0, 0.0, 0.0]);
        s.add_profile_pt([1.0, 0.0, 0.0]);
        let p = s.evaluate(0.0, 4.0);
        // sweep offset should be 4 * unit(0,0,2) = (0,0,4)
        assert!((p[2] - 4.0).abs() < 1e-12, "z={}", p[2]);
    }

    #[test]
    fn extrusion_surface_three_point_profile() {
        let mut s = ExtrusionSurface::new([0.0, 0.0, 1.0]);
        s.add_profile_pt([0.0, 0.0, 0.0]);
        s.add_profile_pt([1.0, 0.0, 0.0]);
        s.add_profile_pt([1.0, 1.0, 0.0]);
        // Total arc = 1 + 1 = 2.
        // u=0.25 -> arc target=0.5 -> midpoint of first segment: (0.5, 0, 0)
        let p = s.evaluate(0.25, 0.0);
        assert!((p[0] - 0.5).abs() < 1e-12, "x={}", p[0]);
        assert!(p[1].abs() < 1e-12, "y={}", p[1]);
        // u=0.75 -> arc target=1.5 -> 0.5 along second segment: (1, 0.5, 0)
        let p2 = s.evaluate(0.75, 0.0);
        assert!((p2[0] - 1.0).abs() < 1e-12, "x={}", p2[0]);
        assert!((p2[1] - 0.5).abs() < 1e-12, "y={}", p2[1]);
    }

    #[test]
    fn extrusion_surface_add_profile_pt_accumulates() {
        let mut s = ExtrusionSurface::new([1.0, 0.0, 0.0]);
        assert_eq!(s.profile.len(), 0);
        s.add_profile_pt([0.0, 0.0, 0.0]);
        assert_eq!(s.profile.len(), 1);
        s.add_profile_pt([0.0, 1.0, 0.0]);
        assert_eq!(s.profile.len(), 2);
    }

    #[test]
    fn extrusion_surface_u_clamped_below_zero() {
        let mut s = ExtrusionSurface::new([0.0, 0.0, 1.0]);
        s.add_profile_pt([0.0, 0.0, 0.0]);
        s.add_profile_pt([1.0, 0.0, 0.0]);
        // u < 0 should clamp to u=0 (first point)
        let p = s.evaluate(-5.0, 0.0);
        assert!(p[0].abs() < 1e-12, "x should be 0.0, got {}", p[0]);
    }

    #[test]
    fn extrusion_surface_u_clamped_above_one() {
        let mut s = ExtrusionSurface::new([0.0, 0.0, 1.0]);
        s.add_profile_pt([0.0, 0.0, 0.0]);
        s.add_profile_pt([1.0, 0.0, 0.0]);
        // u > 1 should clamp to u=1 (last point)
        let p = s.evaluate(99.0, 0.0);
        assert!((p[0] - 1.0).abs() < 1e-12, "x should be 1.0, got {}", p[0]);
    }
}
