// FILE: geom_sweep_algo.rs

/// A primitive swept from a profile along a spine.
// occt-note: BRepSweep — primitive swept from profile along spine
pub struct SweepShape {
    pub nb_profile_edges: usize,
    pub nb_spine_edges: usize,
    pub is_solid: bool,
    pub spine_length: f64,
}

impl SweepShape {
    /// Create a new SweepShape from profile edge count, spine edge count and spine length.
    // occt-note: BRepSweep_Trsf/BRepSweep_NumLinearRegularSweep ctor
    pub fn new(nb_profile_edges: usize, nb_spine_edges: usize, spine_length: f64) -> Self {
        Self {
            nb_profile_edges,
            nb_spine_edges,
            is_solid: false,
            spine_length,
        }
    }

    /// Number of lateral faces generated by the sweep (profile edges × spine edges).
    // occt-note: BRepSweep — lateral face count
    pub fn nb_lateral_faces(&self) -> usize {
        self.nb_profile_edges * self.nb_spine_edges
    }

    /// Number of top and bottom cap faces (2 for solids, 0 for shells).
    // occt-note: BRepSweep — cap face count
    pub fn nb_top_bottom_faces(&self) -> usize {
        if self.is_solid {
            2
        } else {
            0
        }
    }

    /// Total face count: lateral faces plus cap faces.
    // occt-note: BRepSweep — total face count
    pub fn nb_total_faces(&self) -> usize {
        self.nb_lateral_faces() + self.nb_top_bottom_faces()
    }

    /// Whether the swept result is a solid (closed volume).
    // occt-note: BRepSweep — solid flag
    pub fn is_solid(&self) -> bool {
        self.is_solid
    }

    /// Set whether the sweep result should be built as a solid.
    // occt-note: BRepSweep — set solid flag
    pub fn set_solid(&mut self, solid: bool) {
        self.is_solid = solid;
    }

    /// Length of the spine wire along which the profile is swept.
    // occt-note: BRepSweep — spine length
    pub fn spine_length(&self) -> f64 {
        self.spine_length
    }

    /// Approximate volume: spine length × profile edge count (stub).
    // occt-note: BRepSweep — volume approximation stub
    pub fn volume_approx(&self) -> f64 {
        self.spine_length * self.nb_profile_edges as f64
    }
}

/// Result handle for a BRepSweep algorithm build step.
// occt-note: BRepSweep result — mirrors BRepBuilderAPI_MakeShape done/shape state
pub struct SweepAlgoResult {
    is_done: bool,
    nb_shapes: usize,
}

impl SweepAlgoResult {
    /// Create an unbuilt result.
    // occt-note: BRepSweep — initial not-done state
    pub fn new() -> Self {
        Self {
            is_done: false,
            nb_shapes: 0,
        }
    }

    /// Mark the result as built with the given number of output shapes.
    // occt-note: BRepSweep — build completion
    pub fn build(&mut self, nb_shapes: usize) {
        self.nb_shapes = nb_shapes;
        self.is_done = true;
    }

    /// Whether the algorithm has completed successfully.
    // occt: BRepBuilderAPI_MakeShape // ::IsDone
    pub fn is_done(&self) -> bool {
        self.is_done
    }

    /// Number of output shapes produced by the algorithm.
    // occt-note: BRepSweep — generated shape count
    pub fn nb_shapes(&self) -> usize {
        self.nb_shapes
    }
}

impl Default for SweepAlgoResult {
    fn default() -> Self {
        Self::new()
    }
}

/// Linear sweep (prism) of a profile shape along a direction vector.
// occt-ref: BRepPrimAPI_MakePrism // — linear sweep
pub struct SweepLinear {
    shape: SweepShape,
    direction: [f64; 3],
    result: SweepAlgoResult,
}

impl SweepLinear {
    /// Create a new linear sweep from a profile shape and extrusion direction.
    // occt-ref: BRepPrimAPI_MakePrism // ::BRepPrimAPI_MakePrism
    pub fn new(shape: SweepShape, direction: [f64; 3]) -> Self {
        Self {
            shape,
            direction,
            result: SweepAlgoResult::new(),
        }
    }

    /// The extrusion direction vector.
    // occt-ref: BRepPrimAPI_MakePrism // — direction accessor
    pub fn direction(&self) -> [f64; 3] {
        self.direction
    }

    /// Build the prism: total faces plus one edge set per profile edge.
    // occt-ref: BRepPrimAPI_MakePrism // ::Build
    pub fn build(&mut self) {
        let nb = self.shape.nb_total_faces() + self.shape.nb_profile_edges;
        self.result.build(nb);
    }

    /// Whether the build step has completed successfully.
    // occt: BRepBuilderAPI_MakeShape // ::IsDone
    pub fn is_done(&self) -> bool {
        self.result.is_done()
    }

    /// Reference to the algorithm result.
    // occt-ref: BRepPrimAPI_MakePrism // — result accessor
    pub fn result(&self) -> &SweepAlgoResult {
        &self.result
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sweep_shape_lateral_faces() {
        let s = SweepShape::new(4, 3, 10.0);
        assert_eq!(s.nb_lateral_faces(), 12);
    }

    #[test]
    fn sweep_shape_cap_faces_shell() {
        let s = SweepShape::new(4, 3, 10.0);
        assert_eq!(s.nb_top_bottom_faces(), 0);
    }

    #[test]
    fn sweep_shape_cap_faces_solid() {
        let mut s = SweepShape::new(4, 3, 10.0);
        s.set_solid(true);
        assert_eq!(s.nb_top_bottom_faces(), 2);
    }

    #[test]
    fn sweep_shape_total_faces_shell() {
        let s = SweepShape::new(4, 3, 10.0);
        assert_eq!(s.nb_total_faces(), 12);
    }

    #[test]
    fn sweep_shape_total_faces_solid() {
        let mut s = SweepShape::new(4, 3, 10.0);
        s.set_solid(true);
        assert_eq!(s.nb_total_faces(), 14);
    }

    #[test]
    fn sweep_shape_spine_length() {
        let s = SweepShape::new(3, 5, 7.5);
        assert!((s.spine_length() - 7.5).abs() < 1e-12);
    }

    #[test]
    fn sweep_shape_volume_approx_stub() {
        let s = SweepShape::new(4, 3, 2.5);
        assert!((s.volume_approx() - 10.0).abs() < 1e-12);
    }

    #[test]
    fn sweep_algo_result_initial_not_done() {
        let r = SweepAlgoResult::new();
        assert!(!r.is_done());
        assert_eq!(r.nb_shapes(), 0);
    }

    #[test]
    fn sweep_algo_result_after_build() {
        let mut r = SweepAlgoResult::new();
        r.build(7);
        assert!(r.is_done());
        assert_eq!(r.nb_shapes(), 7);
    }

    #[test]
    fn sweep_linear_direction_stored() {
        let s = SweepShape::new(4, 2, 5.0);
        let l = SweepLinear::new(s, [0.0, 0.0, 1.0]);
        let d = l.direction();
        assert!((d[2] - 1.0).abs() < 1e-12);
        assert!(d[0].abs() < 1e-12 && d[1].abs() < 1e-12);
    }

    #[test]
    fn sweep_linear_not_done_before_build() {
        let s = SweepShape::new(4, 2, 5.0);
        let l = SweepLinear::new(s, [1.0, 0.0, 0.0]);
        assert!(!l.is_done());
    }

    #[test]
    fn sweep_linear_done_after_build() {
        let s = SweepShape::new(4, 2, 5.0);
        let mut l = SweepLinear::new(s, [1.0, 0.0, 0.0]);
        l.build();
        assert!(l.is_done());
    }

    #[test]
    fn sweep_linear_nb_shapes_shell() {
        // shell: nb_total_faces=4*2=8, plus nb_profile_edges=4 => 12
        let s = SweepShape::new(4, 2, 5.0);
        let mut l = SweepLinear::new(s, [0.0, 1.0, 0.0]);
        l.build();
        assert_eq!(l.result().nb_shapes(), 12);
    }

    #[test]
    fn sweep_linear_nb_shapes_solid() {
        // solid: nb_total_faces=4*2+2=10, plus nb_profile_edges=4 => 14
        let mut s = SweepShape::new(4, 2, 5.0);
        s.set_solid(true);
        let mut l = SweepLinear::new(s, [0.0, 1.0, 0.0]);
        l.build();
        assert_eq!(l.result().nb_shapes(), 14);
    }
}
