// FILE: geom_pipe_surface.rs
//! `BRepOffsetAPI_MakePipe` / `GeomFill_Pipe` — pipe surface sweep stubs,
//! mirroring OpenCascade's pipe-sweep API from `TKFillet` / `TKG3d`.
//!
//! A pipe surface is generated by sweeping a **profile** curve along a
//! **spine** (rail) curve.  The orientation of the profile at each point
//! along the spine is controlled by a trihedron-propagation mode
//! ([`PipeFillMode`]).
//!
//! ## Types
//!
//! - [`PipeFillMode`]  — trihedron filling-mode selector (`GeomFill_Trihedron`).
//! - [`PipeParams`]    — construction parameters (`BRepOffsetAPI_MakePipe` inputs).
//! - [`PipeResult`]    — build-result stub (`BRepOffsetAPI_MakePipe` outputs).
//! - [`GeomPipe`]      — the pipe builder combining params and result.
//!
//! All implementations are self-contained and use only the Rust standard
//! library.

// ---------------------------------------------------------------------------
// PipeFillMode
// ---------------------------------------------------------------------------

/// Trihedron propagation mode used when sweeping a profile along a spine.
///
/// Mirrors `GeomFill_Trihedron` from OpenCascade (`GeomFill_Trihedron.hxx`).
/// The chosen mode controls how the Frenet / guide frame is transported along
/// the spine, which in turn determines how the profile is oriented at each
/// cross-section.
// occt: GeomFill_Trihedron
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PipeFillMode {
    /// `GeomFill_IsCorrectedFrenet` — Frenet frame with torsion correction to
    /// minimise profile rotation around the spine tangent.
    IsCorrectedFrenet,
    /// `GeomFill_IsFixed` — the trihedron is fixed (does not rotate along
    /// the spine); equivalent to a constant-orientation sweep.
    IsFixed,
    /// `GeomFill_IsFrenet` — classical Frenet–Serret frame (tangent, normal,
    /// binormal).
    IsFrenet,
    /// `GeomFill_IsConstantNormal` — the normal to the profile plane is kept
    /// constant throughout the sweep.
    IsConstantNormal,
    /// `GeomFill_IsBiNormal` — the binormal direction of the Frenet frame is
    /// held fixed.
    IsBiNormal,
    /// `GeomFill_IsQuasiAngular` — quasi-angular (minimum-rotation) frame that
    /// smoothly interpolates the trihedron.
    IsQuasiAngular,
    /// `GeomFill_IsGuideAC` — trihedron driven by an auxiliary guide curve,
    /// using arc-length correspondence.
    IsGuideAC,
    /// `GeomFill_IsGuideACWithContact` — guide-curve AC mode with contact
    /// (the profile stays in contact with the guide).
    IsGuideACWithContact,
    /// `GeomFill_IsGuidePlan` — trihedron driven by an auxiliary guide curve,
    /// planar-correspondence mode.
    IsGuidePlan,
    /// `GeomFill_IsGuidePlanWithContact` — guide-curve planar mode with
    /// contact.
    IsGuidePlanWithContact,
}

// ---------------------------------------------------------------------------
// PipeParams
// ---------------------------------------------------------------------------

/// Construction parameters for a pipe-surface sweep.
///
/// Mirrors the input parameters accepted by `BRepOffsetAPI_MakePipe` and the
/// underlying `GeomFill_Pipe` algorithm.
// occt: BRepOffsetAPI_MakePipe params
#[derive(Clone, Debug)]
pub struct PipeParams {
    /// Total arc-length of the spine curve.
    // occt: spine length (BRepOffsetAPI_MakePipe spine)
    pub spine_length: f64,
    /// Number of control/pole points in the profile curve.
    // occt: profile pole count (GeomFill_Pipe profile poles)
    pub nb_profile_poles: usize,
    /// Trihedron propagation mode controlling profile orientation.
    // occt: GeomFill_Trihedron filling mode
    fill_mode: PipeFillMode,
    /// When `true` the result is a closed solid shell; when `false` it is an
    /// open shell.
    // occt: BRepOffsetAPI_MakePipe ForceApprox / solid flag
    is_solid: bool,
    /// When `true` the algorithm is forced to produce a `C1`-continuous
    /// result even if the spine is only `G1`.
    // occt: BRepOffsetAPI_MakePipe ForceC1
    pub force_c1: bool,
}

impl PipeParams {
    /// Create a new `PipeParams` with sensible defaults:
    /// - fill mode: [`PipeFillMode::IsFrenet`]
    /// - not a solid shell
    /// - `force_c1` disabled
    ///
    /// Mirrors `BRepOffsetAPI_MakePipe(spine, profile)`.
    // occt: BRepOffsetAPI_MakePipe::BRepOffsetAPI_MakePipe
    pub fn new(spine_length: f64, nb_profile_poles: usize) -> Self {
        Self {
            spine_length,
            nb_profile_poles,
            fill_mode: PipeFillMode::IsFrenet,
            is_solid: false,
            force_c1: false,
        }
    }

    /// Set the trihedron propagation mode.
    // occt: BRepOffsetAPI_MakePipe (mode parameter)
    pub fn set_fill_mode(&mut self, mode: PipeFillMode) {
        self.fill_mode = mode;
    }

    /// Return the current trihedron propagation mode.
    // occt: GeomFill_Trihedron accessor
    pub fn fill_mode(&self) -> PipeFillMode {
        self.fill_mode
    }

    /// Set whether the result should be a closed solid shell.
    // occt: BRepOffsetAPI_MakePipe solid flag
    pub fn set_solid(&mut self, solid: bool) {
        self.is_solid = solid;
    }

    /// Return whether the result is a closed solid shell.
    // occt: BRepOffsetAPI_MakePipe solid flag accessor
    pub fn is_solid(&self) -> bool {
        self.is_solid
    }

    /// Return the arc-length of the spine.
    // occt: BRepOffsetAPI_MakePipe spine length
    pub fn spine_length(&self) -> f64 {
        self.spine_length
    }
}

// ---------------------------------------------------------------------------
// PipeResult
// ---------------------------------------------------------------------------

/// Build-result stub for a pipe-surface sweep.
///
/// Mirrors the shape-query methods exposed by `BRepOffsetAPI_MakePipe` after
/// `Build()` has been called.
// occt: BRepOffsetAPI_MakePipe result stub
#[derive(Clone, Debug)]
pub struct PipeResult {
    /// Whether `Build()` has been called and completed successfully.
    // occt: BRepOffsetAPI_MakePipe::IsDone
    pub is_done: bool,
    /// Number of shell faces in the resulting shape.
    // occt: BRepOffsetAPI_MakePipe shape face count
    pub nb_shell_faces: usize,
    /// Number of wire edges in the resulting shape.
    // occt: BRepOffsetAPI_MakePipe shape edge count
    pub nb_wire_edges: usize,
}

impl PipeResult {
    /// Create an uninitialised result (not yet built).
    // occt: BRepOffsetAPI_MakePipe (pre-build state)
    pub fn new() -> Self {
        Self {
            is_done: false,
            nb_shell_faces: 0,
            nb_wire_edges: 0,
        }
    }

    /// Record a successful build with `nb_faces` shell faces and `nb_edges`
    /// wire edges, and mark the result as done.
    ///
    /// Mirrors `BRepOffsetAPI_MakePipe::Build()` side-effects.
    // occt: BRepOffsetAPI_MakePipe::Build
    pub fn build(&mut self, nb_faces: usize, nb_edges: usize) {
        self.nb_shell_faces = nb_faces;
        self.nb_wire_edges = nb_edges;
        self.is_done = true;
    }

    /// Return `true` if [`build`](Self::build) has been called successfully.
    // occt: BRepOffsetAPI_MakePipe::IsDone
    pub fn is_done(&self) -> bool {
        self.is_done
    }

    /// Return the number of shell faces in the built shape.
    // occt: BRepOffsetAPI_MakePipe shape topology
    pub fn nb_shell_faces(&self) -> usize {
        self.nb_shell_faces
    }

    /// Return the number of wire edges in the built shape.
    // occt: BRepOffsetAPI_MakePipe shape topology
    pub fn nb_wire_edges(&self) -> usize {
        self.nb_wire_edges
    }
}

impl Default for PipeResult {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// GeomPipe
// ---------------------------------------------------------------------------

/// Pipe-surface sweep builder.
///
/// Combines [`PipeParams`] (inputs) with a [`PipeResult`] (outputs) and
/// exposes the `Build` / `IsDone` / `Shape` lifecycle that mirrors
/// `BRepOffsetAPI_MakePipe`.
// occt: BRepOffsetAPI_MakePipe
#[derive(Clone, Debug)]
pub struct GeomPipe {
    /// Construction parameters for the sweep.
    // occt: BRepOffsetAPI_MakePipe inputs
    pub params: PipeParams,
    /// Build result (populated after [`build`](Self::build)).
    // occt: BRepOffsetAPI_MakePipe result
    pub result: PipeResult,
}

impl GeomPipe {
    /// Construct a new `GeomPipe` from the given parameters.
    ///
    /// The result is not built until [`build`](Self::build) is called.
    // occt: BRepOffsetAPI_MakePipe::BRepOffsetAPI_MakePipe
    pub fn new(params: PipeParams) -> Self {
        Self {
            params,
            result: PipeResult::new(),
        }
    }

    /// Run the sweep algorithm and populate the [`PipeResult`].
    ///
    /// The number of shell faces is `nb_profile_poles * 2` (one quad-strip
    /// face per profile interval, doubled for both sides), and the number of
    /// wire edges is `nb_profile_poles` (one edge per profile pole seam).
    ///
    /// Mirrors `BRepOffsetAPI_MakePipe::Build()`.
    // occt: BRepOffsetAPI_MakePipe::Build
    pub fn build(&mut self) {
        let nb_faces = self.params.nb_profile_poles * 2;
        let nb_edges = self.params.nb_profile_poles;
        self.result.build(nb_faces, nb_edges);
    }

    /// Return `true` if [`build`](Self::build) has completed successfully.
    // occt: BRepOffsetAPI_MakePipe::IsDone
    pub fn is_done(&self) -> bool {
        self.result.is_done()
    }

    /// Borrow the build result.
    ///
    /// Mirrors `BRepOffsetAPI_MakePipe::Shape()` (returns the constructed
    /// topology; here simplified to the result metadata struct).
    // occt: BRepOffsetAPI_MakePipe::Shape
    pub fn result(&self) -> &PipeResult {
        &self.result
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // ── test 1: PipeFillMode default in PipeParams::new is IsFrenet ───────────
    #[test]
    fn test_pipe_params_default_fill_mode() {
        let p = PipeParams::new(10.0, 4);
        assert_eq!(p.fill_mode(), PipeFillMode::IsFrenet);
    }

    // ── test 2: PipeParams::new stores spine_length and nb_profile_poles ──────
    #[test]
    fn test_pipe_params_new_stores_fields() {
        let p = PipeParams::new(42.5, 6);
        assert_eq!(p.spine_length(), 42.5);
        assert_eq!(p.nb_profile_poles, 6);
        assert!(!p.is_solid());
        assert!(!p.force_c1);
    }

    // ── test 3: set_fill_mode / fill_mode round-trip ──────────────────────────
    #[test]
    fn test_set_fill_mode_round_trip() {
        let mut p = PipeParams::new(1.0, 2);
        for mode in [
            PipeFillMode::IsCorrectedFrenet,
            PipeFillMode::IsFixed,
            PipeFillMode::IsFrenet,
            PipeFillMode::IsConstantNormal,
            PipeFillMode::IsBiNormal,
            PipeFillMode::IsQuasiAngular,
            PipeFillMode::IsGuideAC,
            PipeFillMode::IsGuideACWithContact,
            PipeFillMode::IsGuidePlan,
            PipeFillMode::IsGuidePlanWithContact,
        ] {
            p.set_fill_mode(mode);
            assert_eq!(p.fill_mode(), mode);
        }
    }

    // ── test 4: set_solid / is_solid round-trip ───────────────────────────────
    #[test]
    fn test_set_solid_round_trip() {
        let mut p = PipeParams::new(5.0, 3);
        assert!(!p.is_solid());
        p.set_solid(true);
        assert!(p.is_solid());
        p.set_solid(false);
        assert!(!p.is_solid());
    }

    // ── test 5: PipeResult::new is not done ───────────────────────────────────
    #[test]
    fn test_pipe_result_new_not_done() {
        let r = PipeResult::new();
        assert!(!r.is_done());
        assert_eq!(r.nb_shell_faces(), 0);
        assert_eq!(r.nb_wire_edges(), 0);
    }

    // ── test 6: PipeResult::build sets is_done and topology counts ───────────
    #[test]
    fn test_pipe_result_build() {
        let mut r = PipeResult::new();
        r.build(8, 4);
        assert!(r.is_done());
        assert_eq!(r.nb_shell_faces(), 8);
        assert_eq!(r.nb_wire_edges(), 4);
    }

    // ── test 7: PipeResult::default equals PipeResult::new ───────────────────
    #[test]
    fn test_pipe_result_default() {
        let r = PipeResult::default();
        assert!(!r.is_done());
        assert_eq!(r.nb_shell_faces(), 0);
        assert_eq!(r.nb_wire_edges(), 0);
    }

    // ── test 8: GeomPipe::new is not done before build ────────────────────────
    #[test]
    fn test_geom_pipe_new_not_done() {
        let params = PipeParams::new(20.0, 5);
        let pipe = GeomPipe::new(params);
        assert!(!pipe.is_done());
        assert!(!pipe.result().is_done());
    }

    // ── test 9: GeomPipe::build sets is_done ──────────────────────────────────
    #[test]
    fn test_geom_pipe_build_is_done() {
        let params = PipeParams::new(15.0, 4);
        let mut pipe = GeomPipe::new(params);
        pipe.build();
        assert!(pipe.is_done());
        assert!(pipe.result().is_done());
    }

    // ── test 10: GeomPipe::build computes face/edge counts correctly ──────────
    #[test]
    fn test_geom_pipe_build_topology_counts() {
        let nb_poles = 6_usize;
        let params = PipeParams::new(30.0, nb_poles);
        let mut pipe = GeomPipe::new(params);
        pipe.build();

        // nb_shell_faces = nb_profile_poles * 2
        assert_eq!(pipe.result().nb_shell_faces(), nb_poles * 2);
        // nb_wire_edges = nb_profile_poles
        assert_eq!(pipe.result().nb_wire_edges(), nb_poles);
    }

    // ── test 11: GeomPipe::result borrows the result correctly ────────────────
    #[test]
    fn test_geom_pipe_result_borrow() {
        let params = PipeParams::new(8.0, 3);
        let mut pipe = GeomPipe::new(params);
        pipe.build();

        let res: &PipeResult = pipe.result();
        assert!(res.is_done());
        assert_eq!(res.nb_shell_faces(), 6);
        assert_eq!(res.nb_wire_edges(), 3);
    }

    // ── test 12: GeomPipe params are accessible after build ───────────────────
    #[test]
    fn test_geom_pipe_params_accessible_after_build() {
        let mut params = PipeParams::new(100.0, 8);
        params.set_fill_mode(PipeFillMode::IsCorrectedFrenet);
        params.set_solid(true);

        let mut pipe = GeomPipe::new(params);
        pipe.build();

        assert_eq!(pipe.params.spine_length(), 100.0);
        assert_eq!(pipe.params.nb_profile_poles, 8);
        assert_eq!(pipe.params.fill_mode(), PipeFillMode::IsCorrectedFrenet);
        assert!(pipe.params.is_solid());
    }

    // ── test 13: PipeFillMode variants are all distinct ───────────────────────
    #[test]
    fn test_fill_mode_variants_distinct() {
        let modes = [
            PipeFillMode::IsCorrectedFrenet,
            PipeFillMode::IsFixed,
            PipeFillMode::IsFrenet,
            PipeFillMode::IsConstantNormal,
            PipeFillMode::IsBiNormal,
            PipeFillMode::IsQuasiAngular,
            PipeFillMode::IsGuideAC,
            PipeFillMode::IsGuideACWithContact,
            PipeFillMode::IsGuidePlan,
            PipeFillMode::IsGuidePlanWithContact,
        ];
        // Every adjacent pair must differ.
        for i in 0..modes.len() {
            for j in (i + 1)..modes.len() {
                assert_ne!(modes[i], modes[j], "modes[{i}] == modes[{j}]");
            }
        }
    }

    // ── test 14: PipeParams clone is independent ──────────────────────────────
    #[test]
    fn test_pipe_params_clone_independence() {
        let p1 = PipeParams::new(7.0, 5);
        let mut p2 = p1.clone();
        p2.set_fill_mode(PipeFillMode::IsGuideAC);
        p2.set_solid(true);

        // Original is unchanged.
        assert_eq!(p1.fill_mode(), PipeFillMode::IsFrenet);
        assert!(!p1.is_solid());
    }

    // ── test 15: PipeResult can be built multiple times (last wins) ───────────
    #[test]
    fn test_pipe_result_rebuild() {
        let mut r = PipeResult::new();
        r.build(4, 2);
        assert_eq!(r.nb_shell_faces(), 4);
        r.build(10, 5);
        assert_eq!(r.nb_shell_faces(), 10);
        assert_eq!(r.nb_wire_edges(), 5);
        assert!(r.is_done());
    }
}
