//! `Geom_SurfaceOfRevolution` — surface generated by revolving a profile curve
//! around an axis, mirroring OpenCascade's `Geom_SurfaceOfRevolution`
//! (`src/ModelingData/TKG3d/Geom/Geom_SurfaceOfRevolution.hxx`).
//!
//! ## Parameterization
//!
//! A surface of revolution is defined by:
//! - A **profile curve** (stored as a polyline of 3D points).
//! - A **rotation axis** — a unit direction vector.
//! - An **axis origin** — a point on the axis.
//!
//! The surface is parameterized as:
//!
//! ```text
//! P(U, V) = Rot(U, axis, origin) · profile(V)
//! ```
//!
//! where `U ∈ [0, 2π)` is the revolution angle and `V` indexes the profile
//! (linearly interpolated between stored points).
//!
//! The surface is:
//! - **Closed in U** (periodic with period 2π): rotating by 2π returns to the start.
//! - **Closed in V** only when the profile is a closed loop.
//!
//! ## References
//! - OCCT `Geom_SurfaceOfRevolution` (TKG3d)
//! - ISO 10303-42, surface of revolution definition

use std::f64::consts::PI;

// ─────────────────────── helpers ────────────────────────────────────────────

/// Rotate point `p` around axis `axis` (unit vector) through origin `o` by
/// angle `theta` using the Rodrigues rotation formula.
///
/// `p_rot = o + cos(θ)·(p-o) + sin(θ)·(axis × (p-o)) + (1-cos(θ))·(axis·(p-o))·axis`
#[inline]
fn rotate_point(p: [f64; 3], axis: [f64; 3], o: [f64; 3], theta: f64) -> [f64; 3] {
    let (cos_t, sin_t) = (theta.cos(), theta.sin());
    // r = p - o
    let r = [p[0] - o[0], p[1] - o[1], p[2] - o[2]];
    // axis cross r
    let axr = [
        axis[1] * r[2] - axis[2] * r[1],
        axis[2] * r[0] - axis[0] * r[2],
        axis[0] * r[1] - axis[1] * r[0],
    ];
    // axis dot r
    let dot = axis[0] * r[0] + axis[1] * r[1] + axis[2] * r[2];
    [
        o[0] + cos_t * r[0] + sin_t * axr[0] + (1.0 - cos_t) * dot * axis[0],
        o[1] + cos_t * r[1] + sin_t * axr[1] + (1.0 - cos_t) * dot * axis[1],
        o[2] + cos_t * r[2] + sin_t * axr[2] + (1.0 - cos_t) * dot * axis[2],
    ]
}

/// Normalize a 3-vector. Returns the zero vector if the norm is too small.
#[inline]
fn normalize(v: [f64; 3]) -> [f64; 3] {
    let norm = (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]).sqrt();
    if norm < 1e-14 {
        [0.0, 0.0, 0.0]
    } else {
        [v[0] / norm, v[1] / norm, v[2] / norm]
    }
}

/// Cross product of two 3-vectors.
#[inline]
fn cross(a: [f64; 3], b: [f64; 3]) -> [f64; 3] {
    [
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    ]
}

// ─────────────────────── SurfaceOfRevolution ────────────────────────────────

// occt: Geom_SurfaceOfRevolution
/// `Geom_SurfaceOfRevolution` — a surface obtained by rotating a profile curve
/// around an axis.
///
/// The surface is parameterized by `(U, V)`:
/// - `U ∈ [0, 2π)` is the revolution angle.
/// - `V ∈ [0, profile.len()-1]` indexes the profile polyline (clamped and
///   linearly interpolated between stored sample points).
///
/// The surface is always closed and periodic in U.  It is closed in V only
/// when the first and last profile points coincide.
#[derive(Clone, Debug)]
pub struct SurfaceOfRevolution {
    /// The generating profile polyline in world space.  Each element is an
    /// `[x, y, z]` point.  At least one point is required for evaluation.
    pub profile: Vec<[f64; 3]>,
    /// The unit direction vector of the revolution axis.
    pub axis: [f64; 3],
    /// A point on the revolution axis (the axis origin).
    pub axis_origin: [f64; 3],
}

impl SurfaceOfRevolution {
    // ──────────────────────────── constructors ────────────────────────────────

    /// `Geom_SurfaceOfRevolution(BasisCurve, Axis1)`.
    ///
    /// Create a new empty surface of revolution.
    ///
    /// - `axis`   — the direction of the revolution axis; will be normalised.
    /// - `origin` — any point on the revolution axis.
    ///
    /// Profile points must be added via [`add_profile_point`](Self::add_profile_point)
    /// before calling [`evaluate`](Self::evaluate), [`d1u`](Self::d1u), or
    /// [`d1v`](Self::d1v).
    pub fn new(axis: [f64; 3], origin: [f64; 3]) -> Self {
        SurfaceOfRevolution {
            profile: Vec::new(),
            axis: normalize(axis),
            axis_origin: origin,
        }
    }

    // ──────────────────────────── profile ────────────────────────────────────

    /// Append a point to the profile polyline.
    ///
    /// Points are stored in the order they are added.  The profile parameter
    /// `V` will run from `0` (first point) to `profile.len() - 1` (last point).
    pub fn add_profile_point(&mut self, p: [f64; 3]) {
        self.profile.push(p);
    }

    // ─────────────────────── profile interpolation ───────────────────────────

    /// Linearly interpolate the profile at parameter `v`.
    ///
    /// `v` is clamped to `[0, n-1]` where `n = profile.len()`.  Between
    /// integer indices the profile point is linearly interpolated.
    ///
    /// # Panics
    /// Panics if the profile is empty.
    fn profile_point(&self, v: f64) -> [f64; 3] {
        let n = self.profile.len();
        assert!(n > 0, "Geom_SurfaceOfRevolution: profile is empty");
        if n == 1 {
            return self.profile[0];
        }
        let max = (n - 1) as f64;
        let v = v.max(0.0).min(max);
        let i = (v.floor() as usize).min(n - 2);
        let t = v - i as f64;
        let a = self.profile[i];
        let b = self.profile[i + 1];
        [
            a[0] + t * (b[0] - a[0]),
            a[1] + t * (b[1] - a[1]),
            a[2] + t * (b[2] - a[2]),
        ]
    }

    /// Finite-difference tangent of the profile at `v` (used for `d1v`).
    ///
    /// Uses central differences in the interior and forward/backward differences
    /// at the boundaries.
    fn profile_tangent(&self, v: f64) -> [f64; 3] {
        let n = self.profile.len();
        assert!(n > 0, "Geom_SurfaceOfRevolution: profile is empty");
        if n == 1 {
            return [0.0, 0.0, 0.0];
        }
        let max = (n - 1) as f64;
        let v = v.max(0.0).min(max);
        // Use a small epsilon for central differences.
        let h = 1e-6_f64;
        let v_lo = (v - h).max(0.0);
        let v_hi = (v + h).min(max);
        let dh = v_hi - v_lo;
        if dh < 1e-14 {
            return [0.0, 0.0, 0.0];
        }
        let p_lo = self.profile_point(v_lo);
        let p_hi = self.profile_point(v_hi);
        [
            (p_hi[0] - p_lo[0]) / dh,
            (p_hi[1] - p_lo[1]) / dh,
            (p_hi[2] - p_lo[2]) / dh,
        ]
    }

    // ────────────────────────── evaluation ───────────────────────────────────

    /// `Value(U, V)` — the 3D point on the surface at parameter `(u, v)`.
    ///
    /// `u` is the revolution angle in radians.  `v` linearly indexes the
    /// profile polyline.
    ///
    /// `P(u, v) = Rot(u, axis, origin) · profile(v)`
    pub fn evaluate(&self, u: f64, v: f64) -> [f64; 3] {
        let base = self.profile_point(v);
        rotate_point(base, self.axis, self.axis_origin, u)
    }

    /// `D1U(U, V)` — partial derivative `∂P/∂U` at `(u, v)`.
    ///
    /// For a surface of revolution the U-derivative is the tangent of the
    /// circular arc swept by `P(u, v)`.  By Rodrigues:
    ///
    /// `∂P/∂U = axis × (P(u,v) - axis_origin)`
    ///
    /// (the same formula as angular velocity applied to the surface point).
    pub fn d1u(&self, u: f64, v: f64) -> [f64; 3] {
        let p = self.evaluate(u, v);
        let r = [
            p[0] - self.axis_origin[0],
            p[1] - self.axis_origin[1],
            p[2] - self.axis_origin[2],
        ];
        cross(self.axis, r)
    }

    /// `D1V(U, V)` — partial derivative `∂P/∂V` at `(u, v)`.
    ///
    /// The V-derivative is the profile tangent rotated by `u`:
    ///
    /// `∂P/∂V = Rot(u, axis, origin) · profile'(v)` (rotation applied to the
    /// tangent vector, treating the origin as a fixed point for the vector part).
    pub fn d1v(&self, u: f64, v: f64) -> [f64; 3] {
        let base_tangent = self.profile_tangent(v);
        // Rotate the tangent vector (a free vector, so origin does not matter;
        // we pass [0,0,0] as the translation anchor and rotate as a vector).
        // For a free vector Rodrigues simplifies to:
        //   v_rot = cos(u)*t + sin(u)*(axis × t) + (1-cos(u))*(axis·t)*axis
        let t = base_tangent;
        let (cos_u, sin_u) = (u.cos(), u.sin());
        let axr = cross(self.axis, t);
        let dot = self.axis[0] * t[0] + self.axis[1] * t[1] + self.axis[2] * t[2];
        [
            cos_u * t[0] + sin_u * axr[0] + (1.0 - cos_u) * dot * self.axis[0],
            cos_u * t[1] + sin_u * axr[1] + (1.0 - cos_u) * dot * self.axis[1],
            cos_u * t[2] + sin_u * axr[2] + (1.0 - cos_u) * dot * self.axis[2],
        ]
    }

    // ──────────────────────── topology queries ────────────────────────────────

    /// `IsUClosed()` — always `true`; the revolution surface is periodic in U.
    ///
    /// After a full rotation of 2π the surface returns to the starting position.
    pub fn is_u_closed(&self) -> bool {
        true
    }

    /// `IsVClosed()` — `true` when the first and last profile points coincide.
    ///
    /// A closed profile (e.g. a circle or closed polyline) produces a V-closed
    /// surface (like a torus).
    pub fn is_v_closed(&self) -> bool {
        if self.profile.len() < 2 {
            return false;
        }
        let first = self.profile[0];
        let last = *self.profile.last().unwrap();
        let dx = first[0] - last[0];
        let dy = first[1] - last[1];
        let dz = first[2] - last[2];
        (dx * dx + dy * dy + dz * dz).sqrt() < 1e-10
    }
}

// ──────────────────────── revolve_profile ────────────────────────────────────

/// Revolve a profile polyline around an axis and sample the resulting surface.
///
/// Returns a 2-D grid `grid[i][j]` where:
/// - `i ∈ [0, n]`   indexes the revolution angle `U = i * angle / n`.
/// - `j ∈ [0, pts.len()-1]` indexes the profile point.
///
/// Parameters:
/// - `pts`   — the profile polyline to revolve.
/// - `axis`  — the revolution axis direction (will be normalised).
/// - `angle` — the total sweep angle in radians (use `2π` for a full revolution).
/// - `n`     — the number of angular divisions (the angle is divided into `n`
///             equal steps; the returned grid has `n + 1` rows so that both the
///             start and end sections are included).
///
/// # Examples
///
/// ```no_run
/// use ironstream::geom_surface_of_revolution::revolve_profile;
/// use std::f64::consts::PI;
///
/// let profile = vec![[1.0, 0.0, 0.0], [1.0, 0.0, 1.0]];
/// let grid = revolve_profile(&profile, [0.0, 0.0, 1.0], 2.0 * PI, 8);
/// assert_eq!(grid.len(), 9);          // n + 1 angle samples
/// assert_eq!(grid[0].len(), 2);       // one entry per profile point
/// ```
pub fn revolve_profile(
    pts: &[[f64; 3]],
    axis: [f64; 3],
    angle: f64,
    n: usize,
) -> Vec<Vec<[f64; 3]>> {
    let axis_n = normalize(axis);
    let origin = [0.0_f64; 3]; // revolve around the world origin on the given axis
    let steps = if n == 0 { 1 } else { n };
    let mut grid: Vec<Vec<[f64; 3]>> = Vec::with_capacity(steps + 1);
    for i in 0..=steps {
        let theta = angle * (i as f64) / (steps as f64);
        let row: Vec<[f64; 3]> = pts
            .iter()
            .map(|&p| rotate_point(p, axis_n, origin, theta))
            .collect();
        grid.push(row);
    }
    grid
}

// ─────────────────────────────── tests ───────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    const TOL: f64 = 1e-9;

    fn close(a: [f64; 3], b: [f64; 3]) -> bool {
        let d = [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
        (d[0] * d[0] + d[1] * d[1] + d[2] * d[2]).sqrt() < TOL
    }

    // ── test 1: new() normalizes the axis ────────────────────────────────────
    #[test]
    fn test_new_normalizes_axis() {
        let surf = SurfaceOfRevolution::new([0.0, 0.0, 5.0], [0.0, 0.0, 0.0]);
        let n = surf.axis;
        let norm = (n[0] * n[0] + n[1] * n[1] + n[2] * n[2]).sqrt();
        assert!((norm - 1.0).abs() < TOL);
        assert!((n[2] - 1.0).abs() < TOL);
    }

    // ── test 2: is_u_closed is always true ───────────────────────────────────
    #[test]
    fn test_is_u_closed() {
        let mut surf = SurfaceOfRevolution::new([0.0, 0.0, 1.0], [0.0, 0.0, 0.0]);
        surf.add_profile_point([1.0, 0.0, 0.0]);
        assert!(surf.is_u_closed());
    }

    // ── test 3: is_v_closed — open profile ───────────────────────────────────
    #[test]
    fn test_is_v_closed_open() {
        let mut surf = SurfaceOfRevolution::new([0.0, 0.0, 1.0], [0.0, 0.0, 0.0]);
        surf.add_profile_point([1.0, 0.0, 0.0]);
        surf.add_profile_point([1.0, 0.0, 1.0]);
        assert!(!surf.is_v_closed());
    }

    // ── test 4: is_v_closed — closed profile ─────────────────────────────────
    #[test]
    fn test_is_v_closed_closed() {
        let mut surf = SurfaceOfRevolution::new([0.0, 0.0, 1.0], [0.0, 0.0, 0.0]);
        surf.add_profile_point([1.0, 0.0, 0.0]);
        surf.add_profile_point([2.0, 0.0, 0.0]);
        surf.add_profile_point([1.0, 0.0, 0.0]); // same as first
        assert!(surf.is_v_closed());
    }

    // ── test 5: evaluate — single point, revolution around Z ─────────────────
    #[test]
    fn test_evaluate_cylinder() {
        let mut surf = SurfaceOfRevolution::new([0.0, 0.0, 1.0], [0.0, 0.0, 0.0]);
        surf.add_profile_point([1.0, 0.0, 0.0]);

        // U=0 => unchanged
        let p0 = surf.evaluate(0.0, 0.0);
        assert!(close(p0, [1.0, 0.0, 0.0]));

        // U=π/2 => rotated to (0, 1, 0)
        let p90 = surf.evaluate(PI / 2.0, 0.0);
        assert!(close(p90, [0.0, 1.0, 0.0]));

        // U=π => (-1, 0, 0)
        let p180 = surf.evaluate(PI, 0.0);
        assert!(close(p180, [-1.0, 0.0, 0.0]));

        // U=2π => back to (1, 0, 0)
        let p360 = surf.evaluate(2.0 * PI, 0.0);
        assert!(close(p360, [1.0, 0.0, 0.0]));
    }

    // ── test 6: evaluate — two-point profile (cylinder with height) ──────────
    #[test]
    fn test_evaluate_two_point_profile() {
        let mut surf = SurfaceOfRevolution::new([0.0, 0.0, 1.0], [0.0, 0.0, 0.0]);
        surf.add_profile_point([1.0, 0.0, 0.0]);
        surf.add_profile_point([1.0, 0.0, 2.0]);

        // V=0 => bottom, V=1 => top
        let bottom = surf.evaluate(0.0, 0.0);
        let top = surf.evaluate(0.0, 1.0);
        assert!(close(bottom, [1.0, 0.0, 0.0]));
        assert!(close(top, [1.0, 0.0, 2.0]));

        // Mid-point V=0.5 => (1, 0, 1)
        let mid = surf.evaluate(0.0, 0.5);
        assert!(close(mid, [1.0, 0.0, 1.0]));

        // At U=π/2, V=0 => (0, 1, 0)
        let rotated = surf.evaluate(PI / 2.0, 0.0);
        assert!(close(rotated, [0.0, 1.0, 0.0]));
    }

    // ── test 7: d1u is perpendicular to the radius vector ────────────────────
    #[test]
    fn test_d1u_perpendicular_to_radius() {
        let mut surf = SurfaceOfRevolution::new([0.0, 0.0, 1.0], [0.0, 0.0, 0.0]);
        surf.add_profile_point([2.0, 0.0, 0.0]);

        let u = PI / 4.0;
        let p = surf.evaluate(u, 0.0);
        let du = surf.d1u(u, 0.0);

        // du should be perpendicular to (p - origin) in the XY plane
        let dot = p[0] * du[0] + p[1] * du[1] + p[2] * du[2];
        assert!(dot.abs() < 1e-10);

        // du should also be perpendicular to the axis
        let dot_axis = du[0] * surf.axis[0] + du[1] * surf.axis[1] + du[2] * surf.axis[2];
        assert!(dot_axis.abs() < 1e-10);
    }

    // ── test 8: d1u magnitude equals radius for unit axis ────────────────────
    #[test]
    fn test_d1u_magnitude() {
        let r = 3.0_f64;
        let mut surf = SurfaceOfRevolution::new([0.0, 0.0, 1.0], [0.0, 0.0, 0.0]);
        surf.add_profile_point([r, 0.0, 0.0]);

        for i in 0..8 {
            let u = (i as f64) * PI / 4.0;
            let du = surf.d1u(u, 0.0);
            let mag = (du[0] * du[0] + du[1] * du[1] + du[2] * du[2]).sqrt();
            assert!((mag - r).abs() < 1e-9, "u={u} mag={mag} expected {r}");
        }
    }

    // ── test 9: d1v along Z-axis profile ─────────────────────────────────────
    #[test]
    fn test_d1v_along_z() {
        let mut surf = SurfaceOfRevolution::new([0.0, 0.0, 1.0], [0.0, 0.0, 0.0]);
        surf.add_profile_point([1.0, 0.0, 0.0]);
        surf.add_profile_point([1.0, 0.0, 1.0]);

        // At U=0 the profile tangent is (0, 0, 1); rotation by 0 keeps it (0, 0, 1).
        let dv = surf.d1v(0.0, 0.5);
        assert!((dv[0]).abs() < 1e-6);
        assert!((dv[1]).abs() < 1e-6);
        assert!((dv[2] - 1.0).abs() < 1e-6);

        // At U=π/2 the tangent (0,0,1) rotated around Z is still (0,0,1).
        let dv2 = surf.d1v(PI / 2.0, 0.5);
        assert!((dv2[0]).abs() < 1e-6);
        assert!((dv2[1]).abs() < 1e-6);
        assert!((dv2[2] - 1.0).abs() < 1e-6);
    }

    // ── test 10: revolve_profile — correct grid dimensions ───────────────────
    #[test]
    fn test_revolve_profile_dimensions() {
        let pts = vec![[1.0, 0.0, 0.0], [1.0, 0.0, 1.0], [1.0, 0.0, 2.0]];
        let grid = revolve_profile(&pts, [0.0, 0.0, 1.0], 2.0 * PI, 8);
        assert_eq!(grid.len(), 9, "expected n+1=9 rows");
        for row in &grid {
            assert_eq!(row.len(), 3, "expected 3 columns (one per profile point)");
        }
    }

    // ── test 11: revolve_profile — first row equals input pts ────────────────
    #[test]
    fn test_revolve_profile_first_row() {
        let pts = vec![[1.0, 0.0, 0.0], [2.0, 0.0, 0.5]];
        let grid = revolve_profile(&pts, [0.0, 0.0, 1.0], 2.0 * PI, 4);
        // The first row (angle=0) should match the input points.
        assert!(close(grid[0][0], pts[0]));
        assert!(close(grid[0][1], pts[1]));
    }

    // ── test 12: revolve_profile — last row for full revolution matches first ─
    #[test]
    fn test_revolve_profile_full_revolution() {
        let pts = vec![[1.0, 0.0, 0.0], [1.0, 0.0, 1.0]];
        let grid = revolve_profile(&pts, [0.0, 0.0, 1.0], 2.0 * PI, 16);
        let first = &grid[0];
        let last = &grid[16];
        assert!(close(first[0], last[0]));
        assert!(close(first[1], last[1]));
    }

    // ── test 13: revolve_profile — half revolution rotates correctly ──────────
    #[test]
    fn test_revolve_profile_half_revolution() {
        let pts = vec![[1.0, 0.0, 0.0]];
        let grid = revolve_profile(&pts, [0.0, 0.0, 1.0], PI, 2);
        // grid[0][0] = (1, 0, 0), grid[1][0] = (0, 1, 0), grid[2][0] = (-1, 0, 0)
        assert!(close(grid[0][0], [1.0, 0.0, 0.0]));
        assert!(close(grid[1][0], [0.0, 1.0, 0.0]));
        assert!(close(grid[2][0], [-1.0, 0.0, 0.0]));
    }

    // ── test 14: revolve_profile — n=0 does not panic ────────────────────────
    #[test]
    fn test_revolve_profile_n_zero() {
        let pts = vec![[1.0, 0.0, 0.0]];
        let grid = revolve_profile(&pts, [0.0, 0.0, 1.0], 2.0 * PI, 0);
        // n=0 treated as 1 step, grid has 2 rows
        assert_eq!(grid.len(), 2);
    }
}
