// FILE: crates/ironstream/src/geom_surface_of_linear_extrusion.rs
//! `SurfaceOfLinearExtrusion` — a ruled surface formed by sweeping a profile
//! curve along a fixed direction vector, mirroring OpenCascade's
//! `Geom_SurfaceOfLinearExtrusion`.
//!
//! The U parameter runs along the profile curve; the V parameter runs along
//! the extrusion direction.  The surface is therefore defined as:
//!
//! ```text
//! S(u, v) = C(u) + v * Dir
//! ```
//!
//! where `C(u)` is the profile point at parameter `u` and `Dir` is the
//! (unit) extrusion direction.
//!
//! All implementations use **only** the Rust standard library.

// ---------------------------------------------------------------------------
// SurfaceOfLinearExtrusion
// ---------------------------------------------------------------------------

/// A surface generated by translating a profile curve along a fixed direction.
///
/// Mirrors `Geom_SurfaceOfLinearExtrusion` from OpenCascade.
// occt: Geom_SurfaceOfLinearExtrusion
#[derive(Clone, Debug)]
pub struct SurfaceOfLinearExtrusion {
    /// Ordered sequence of 3-D points that define the profile curve.
    /// Parameter `u` in `[0, profile.len() - 1]` indexes this polyline.
    pub profile: Vec<[f64; 3]>,
    /// The extrusion direction vector (need not be unit length on construction,
    /// but is normalised internally before use in evaluations).
    pub direction: [f64; 3],
}

impl SurfaceOfLinearExtrusion {
    /// Construct an empty surface with the given extrusion direction.
    ///
    /// The direction is stored as-is; it is normalised on demand inside
    /// [`evaluate`](Self::evaluate), [`d1u`](Self::d1u), and
    /// [`d1v`](Self::d1v).
    pub fn new(dir: [f64; 3]) -> Self {
        Self {
            profile: Vec::new(),
            direction: dir,
        }
    }

    /// Append a point to the end of the profile curve.
    pub fn add_profile_point(&mut self, p: [f64; 3]) {
        self.profile.push(p);
    }

    // occt: Geom_SurfaceOfLinearExtrusion::Value
    /// Evaluate the surface at parametric coordinates `(u, v)`.
    ///
    /// - `u` — parameter along the profile curve; clamped to
    ///   `[0, profile.len() - 1]` and linearly interpolated between adjacent
    ///   profile points.  Returns `[0, 0, 0]` when the profile is empty.
    /// - `v` — parameter along the extrusion direction.
    ///
    /// `S(u, v) = C(u) + v * unit(direction)`
    pub fn evaluate(&self, u: f64, v: f64) -> [f64; 3] {
        let c = self.profile_point(u);
        let d = self.unit_direction();
        [c[0] + v * d[0], c[1] + v * d[1], c[2] + v * d[2]]
    }

    // occt: Geom_SurfaceOfLinearExtrusion::D1U (partial derivative in U)
    /// First-order partial derivative of the surface with respect to `u`.
    ///
    /// Computed as the finite-difference tangent of the piecewise-linear
    /// profile.  Returns `[0, 0, 0]` when the profile has fewer than two
    /// points.
    pub fn d1u(&self, u: f64, _v: f64) -> [f64; 3] {
        let n = self.profile.len();
        if n < 2 {
            return [0.0, 0.0, 0.0];
        }
        // Determine the segment containing u.
        let u_clamped = u.clamp(0.0, (n - 1) as f64);
        let i = (u_clamped.floor() as usize).min(n - 2);
        let a = self.profile[i];
        let b = self.profile[i + 1];
        // Tangent of the linear segment (constant over the segment).
        [b[0] - a[0], b[1] - a[1], b[2] - a[2]]
    }

    // occt: Geom_SurfaceOfLinearExtrusion::D1V (partial derivative in V)
    /// First-order partial derivative of the surface with respect to `v`.
    ///
    /// Equal to the (unit) extrusion direction, independent of `(u, v)`.
    pub fn d1v(&self, _u: f64, _v: f64) -> [f64; 3] {
        self.unit_direction()
    }

    // occt: Geom_SurfaceOfLinearExtrusion::BasisCurve value
    /// Evaluate the profile curve at parameter `u`.
    ///
    /// `u` is clamped to `[0, profile.len() - 1]` and linearly interpolated
    /// between adjacent profile points.  Returns `[0, 0, 0]` when the profile
    /// is empty.
    pub fn profile_point(&self, u: f64) -> [f64; 3] {
        let n = self.profile.len();
        if n == 0 {
            return [0.0, 0.0, 0.0];
        }
        if n == 1 {
            return self.profile[0];
        }
        let u_clamped = u.clamp(0.0, (n - 1) as f64);
        let i = (u_clamped.floor() as usize).min(n - 2);
        let t = u_clamped - i as f64; // fractional part in [0, 1]
        let a = self.profile[i];
        let b = self.profile[i + 1];
        [
            a[0] + t * (b[0] - a[0]),
            a[1] + t * (b[1] - a[1]),
            a[2] + t * (b[2] - a[2]),
        ]
    }

    // occt: Geom_SurfaceOfLinearExtrusion::IsUClosed
    /// Returns `false`; an open piecewise-linear profile is not closed in U.
    ///
    /// Would return `true` for a closed periodic profile curve (e.g. a
    /// circle), but that case is out of scope for this stub.
    pub fn is_u_closed(&self) -> bool {
        false
    }

    // ---------------------------------------------------------------------------
    // Internal helpers
    // ---------------------------------------------------------------------------

    /// Return the extrusion direction normalised to unit length.
    ///
    /// Falls back to `[0, 0, 1]` if the stored direction has zero magnitude.
    fn unit_direction(&self) -> [f64; 3] {
        let [dx, dy, dz] = self.direction;
        let len = (dx * dx + dy * dy + dz * dz).sqrt();
        if len < f64::EPSILON {
            [0.0, 0.0, 1.0]
        } else {
            [dx / len, dy / len, dz / len]
        }
    }
}

// ---------------------------------------------------------------------------
// Free function: extrude_curve
// ---------------------------------------------------------------------------

/// Build a grid of surface points by extruding a polyline profile along a
/// direction, sampling `v` uniformly from `0` to `len`.
///
/// - `pts`   — profile points forming the base curve.
/// - `dir`   — extrusion direction (normalised internally).
/// - `len`   — total extrusion length.
///
/// Returns a `Vec<Vec<[f64; 3]>>` where each inner `Vec` corresponds to one
/// profile point, and contains two entries: the point at `v = 0` (i.e. the
/// profile point itself) and the translated point at `v = len`.
///
/// The resulting grid has dimensions `pts.len() × 2`.
///
/// # Example
///
/// ```
/// # use ironstream::geom_surface_of_linear_extrusion::extrude_curve;
/// let pts = vec![[0.0, 0.0, 0.0], [1.0, 0.0, 0.0]];
/// let grid = extrude_curve(&pts, [0.0, 0.0, 1.0], 5.0);
/// assert_eq!(grid.len(), 2);
/// assert_eq!(grid[0].len(), 2);
/// assert_eq!(grid[0][1], [0.0, 0.0, 5.0]);
/// assert_eq!(grid[1][1], [1.0, 0.0, 5.0]);
/// ```
pub fn extrude_curve(pts: &[[f64; 3]], dir: [f64; 3], len: f64) -> Vec<Vec<[f64; 3]>> {
    let mut surf = SurfaceOfLinearExtrusion::new(dir);
    for &p in pts {
        surf.add_profile_point(p);
    }
    let d = surf.unit_direction();
    pts.iter()
        .map(|&p| {
            let v0 = p;
            let v1 = [p[0] + len * d[0], p[1] + len * d[1], p[2] + len * d[2]];
            vec![v0, v1]
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::f64::consts::SQRT_2;

    const EPS: f64 = 1e-12;

    fn near(a: f64, b: f64) {
        assert!(
            (a - b).abs() < EPS,
            "expected {a} ≈ {b}, diff={}",
            (a - b).abs()
        );
    }

    fn vec_near(a: [f64; 3], b: [f64; 3]) {
        near(a[0], b[0]);
        near(a[1], b[1]);
        near(a[2], b[2]);
    }

    // -----------------------------------------------------------------------
    // SurfaceOfLinearExtrusion::new
    // -----------------------------------------------------------------------

    #[test]
    fn new_stores_direction_and_empty_profile() {
        let s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        assert_eq!(s.direction, [0.0, 0.0, 1.0]);
        assert!(s.profile.is_empty());
    }

    #[test]
    fn new_arbitrary_direction() {
        let s = SurfaceOfLinearExtrusion::new([1.0, 2.0, 3.0]);
        assert_eq!(s.direction, [1.0, 2.0, 3.0]);
    }

    // -----------------------------------------------------------------------
    // add_profile_point
    // -----------------------------------------------------------------------

    #[test]
    fn add_profile_point_appends() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        s.add_profile_point([1.0, 2.0, 3.0]);
        s.add_profile_point([4.0, 5.0, 6.0]);
        assert_eq!(s.profile.len(), 2);
        assert_eq!(s.profile[0], [1.0, 2.0, 3.0]);
        assert_eq!(s.profile[1], [4.0, 5.0, 6.0]);
    }

    // -----------------------------------------------------------------------
    // profile_point
    // -----------------------------------------------------------------------

    #[test]
    fn profile_point_empty_returns_origin() {
        let s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        vec_near(s.profile_point(0.0), [0.0, 0.0, 0.0]);
        vec_near(s.profile_point(5.0), [0.0, 0.0, 0.0]);
    }

    #[test]
    fn profile_point_single_point_always_returns_it() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        s.add_profile_point([3.0, 4.0, 5.0]);
        vec_near(s.profile_point(0.0), [3.0, 4.0, 5.0]);
        vec_near(s.profile_point(10.0), [3.0, 4.0, 5.0]);
        vec_near(s.profile_point(-1.0), [3.0, 4.0, 5.0]);
    }

    #[test]
    fn profile_point_at_integer_params() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        s.add_profile_point([0.0, 0.0, 0.0]);
        s.add_profile_point([1.0, 0.0, 0.0]);
        s.add_profile_point([2.0, 0.0, 0.0]);
        vec_near(s.profile_point(0.0), [0.0, 0.0, 0.0]);
        vec_near(s.profile_point(1.0), [1.0, 0.0, 0.0]);
        vec_near(s.profile_point(2.0), [2.0, 0.0, 0.0]);
    }

    #[test]
    fn profile_point_midpoint_interpolation() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        s.add_profile_point([0.0, 0.0, 0.0]);
        s.add_profile_point([2.0, 4.0, 0.0]);
        vec_near(s.profile_point(0.5), [1.0, 2.0, 0.0]);
    }

    #[test]
    fn profile_point_clamps_below_zero() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        s.add_profile_point([7.0, 8.0, 9.0]);
        s.add_profile_point([1.0, 2.0, 3.0]);
        vec_near(s.profile_point(-5.0), s.profile_point(0.0));
    }

    #[test]
    fn profile_point_clamps_above_max() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        s.add_profile_point([0.0, 0.0, 0.0]);
        s.add_profile_point([1.0, 0.0, 0.0]);
        vec_near(s.profile_point(100.0), [1.0, 0.0, 0.0]);
    }

    // -----------------------------------------------------------------------
    // evaluate
    // -----------------------------------------------------------------------

    #[test]
    fn evaluate_v_zero_returns_profile_point() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        s.add_profile_point([1.0, 2.0, 0.0]);
        s.add_profile_point([3.0, 4.0, 0.0]);
        vec_near(s.evaluate(0.0, 0.0), [1.0, 2.0, 0.0]);
        vec_near(s.evaluate(1.0, 0.0), [3.0, 4.0, 0.0]);
    }

    #[test]
    fn evaluate_translates_along_unit_direction() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        s.add_profile_point([0.0, 0.0, 0.0]);
        // v = 5, direction = [0,0,1] → point should be [0,0,5]
        vec_near(s.evaluate(0.0, 5.0), [0.0, 0.0, 5.0]);
    }

    #[test]
    fn evaluate_normalises_direction() {
        // Direction [0, 0, 2] should behave identically to [0, 0, 1] for unit v.
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 2.0]);
        s.add_profile_point([1.0, 0.0, 0.0]);
        // unit dir = [0,0,1], so S(0, 3) = [1, 0, 3]
        vec_near(s.evaluate(0.0, 3.0), [1.0, 0.0, 3.0]);
    }

    #[test]
    fn evaluate_with_diagonal_direction() {
        // Direction [1,1,0] normalised → [1/√2, 1/√2, 0]
        let mut s = SurfaceOfLinearExtrusion::new([1.0, 1.0, 0.0]);
        s.add_profile_point([0.0, 0.0, 0.0]);
        let pt = s.evaluate(0.0, SQRT_2);
        // v * unit([1,1,0]) * √2 = [1, 1, 0]
        assert!((pt[0] - 1.0).abs() < 1e-12, "x={}", pt[0]);
        assert!((pt[1] - 1.0).abs() < 1e-12, "y={}", pt[1]);
        assert!((pt[2] - 0.0).abs() < 1e-12, "z={}", pt[2]);
    }

    // -----------------------------------------------------------------------
    // d1u
    // -----------------------------------------------------------------------

    #[test]
    fn d1u_empty_profile_returns_zero() {
        let s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        vec_near(s.d1u(0.0, 0.0), [0.0, 0.0, 0.0]);
    }

    #[test]
    fn d1u_single_point_returns_zero() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        s.add_profile_point([1.0, 2.0, 3.0]);
        vec_near(s.d1u(0.0, 0.0), [0.0, 0.0, 0.0]);
    }

    #[test]
    fn d1u_two_points_returns_segment_tangent() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        s.add_profile_point([0.0, 0.0, 0.0]);
        s.add_profile_point([3.0, 4.0, 0.0]);
        vec_near(s.d1u(0.5, 0.0), [3.0, 4.0, 0.0]);
        vec_near(s.d1u(0.0, 0.0), [3.0, 4.0, 0.0]);
    }

    #[test]
    fn d1u_is_independent_of_v() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        s.add_profile_point([0.0, 0.0, 0.0]);
        s.add_profile_point([1.0, 0.0, 0.0]);
        let a = s.d1u(0.5, 0.0);
        let b = s.d1u(0.5, 100.0);
        vec_near(a, b);
    }

    #[test]
    fn d1u_changes_segment_between_profile_points() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        s.add_profile_point([0.0, 0.0, 0.0]);
        s.add_profile_point([1.0, 0.0, 0.0]); // segment 0→1: tangent [1,0,0]
        s.add_profile_point([1.0, 1.0, 0.0]); // segment 1→2: tangent [0,1,0]
        vec_near(s.d1u(0.5, 0.0), [1.0, 0.0, 0.0]);
        vec_near(s.d1u(1.5, 0.0), [0.0, 1.0, 0.0]);
    }

    // -----------------------------------------------------------------------
    // d1v
    // -----------------------------------------------------------------------

    #[test]
    fn d1v_equals_unit_direction() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 3.0]);
        s.add_profile_point([0.0, 0.0, 0.0]);
        vec_near(s.d1v(0.0, 0.0), [0.0, 0.0, 1.0]);
    }

    #[test]
    fn d1v_is_constant_over_surface() {
        let mut s = SurfaceOfLinearExtrusion::new([1.0, 0.0, 0.0]);
        s.add_profile_point([5.0, 3.0, -1.0]);
        s.add_profile_point([6.0, 3.0, -1.0]);
        let a = s.d1v(0.0, 0.0);
        let b = s.d1v(0.7, 42.5);
        vec_near(a, b);
    }

    #[test]
    fn d1v_is_unit_length() {
        let mut s = SurfaceOfLinearExtrusion::new([3.0, 4.0, 0.0]); // mag = 5
        s.add_profile_point([0.0, 0.0, 0.0]);
        let d = s.d1v(0.0, 0.0);
        let len = (d[0] * d[0] + d[1] * d[1] + d[2] * d[2]).sqrt();
        assert!((len - 1.0).abs() < 1e-12, "len={len}");
        near(d[0], 3.0 / 5.0);
        near(d[1], 4.0 / 5.0);
    }

    // -----------------------------------------------------------------------
    // is_u_closed
    // -----------------------------------------------------------------------

    #[test]
    fn is_u_closed_always_false() {
        let s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        assert!(!s.is_u_closed());
        let mut s2 = SurfaceOfLinearExtrusion::new([0.0, 1.0, 0.0]);
        s2.add_profile_point([0.0, 0.0, 0.0]);
        s2.add_profile_point([1.0, 0.0, 0.0]);
        assert!(!s2.is_u_closed());
    }

    // -----------------------------------------------------------------------
    // unit_direction fallback
    // -----------------------------------------------------------------------

    #[test]
    fn zero_direction_falls_back_to_z_axis() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 0.0]);
        s.add_profile_point([0.0, 0.0, 0.0]);
        // d1v should return the fallback [0,0,1]
        vec_near(s.d1v(0.0, 0.0), [0.0, 0.0, 1.0]);
        vec_near(s.evaluate(0.0, 2.0), [0.0, 0.0, 2.0]);
    }

    // -----------------------------------------------------------------------
    // Clone / Debug
    // -----------------------------------------------------------------------

    #[test]
    fn surface_is_clone() {
        let mut s = SurfaceOfLinearExtrusion::new([0.0, 0.0, 1.0]);
        s.add_profile_point([1.0, 2.0, 3.0]);
        let s2 = s.clone();
        assert_eq!(s2.direction, s.direction);
        assert_eq!(s2.profile.len(), s.profile.len());
    }

    #[test]
    fn surface_debug_format_contains_direction() {
        let s = SurfaceOfLinearExtrusion::new([1.0, 2.0, 3.0]);
        let dbg = format!("{:?}", s);
        assert!(dbg.contains("direction"), "debug missing 'direction': {dbg}");
    }

    // -----------------------------------------------------------------------
    // extrude_curve
    // -----------------------------------------------------------------------

    #[test]
    fn extrude_curve_empty_pts_returns_empty() {
        let grid = extrude_curve(&[], [0.0, 0.0, 1.0], 5.0);
        assert!(grid.is_empty());
    }

    #[test]
    fn extrude_curve_single_point_grid_shape() {
        let grid = extrude_curve(&[[1.0, 2.0, 3.0]], [0.0, 0.0, 1.0], 5.0);
        assert_eq!(grid.len(), 1);
        assert_eq!(grid[0].len(), 2);
    }

    #[test]
    fn extrude_curve_v0_is_profile_point() {
        let pts = vec![[1.0, 0.0, 0.0], [2.0, 0.0, 0.0]];
        let grid = extrude_curve(&pts, [0.0, 0.0, 1.0], 3.0);
        vec_near(grid[0][0], [1.0, 0.0, 0.0]);
        vec_near(grid[1][0], [2.0, 0.0, 0.0]);
    }

    #[test]
    fn extrude_curve_v1_is_translated_point() {
        let pts = vec![[0.0, 0.0, 0.0], [1.0, 0.0, 0.0]];
        let grid = extrude_curve(&pts, [0.0, 0.0, 1.0], 5.0);
        vec_near(grid[0][1], [0.0, 0.0, 5.0]);
        vec_near(grid[1][1], [1.0, 0.0, 5.0]);
    }

    #[test]
    fn extrude_curve_normalises_direction() {
        // Direction [0, 0, 2], len=2 → normalised [0,0,1]; v = 3 → z = 3
        let pts = vec![[0.0, 0.0, 0.0]];
        let grid = extrude_curve(&pts, [0.0, 0.0, 2.0], 3.0);
        vec_near(grid[0][1], [0.0, 0.0, 3.0]);
    }

    #[test]
    fn extrude_curve_multiple_points() {
        let pts = vec![
            [0.0, 0.0, 0.0],
            [1.0, 0.0, 0.0],
            [2.0, 0.0, 0.0],
        ];
        let grid = extrude_curve(&pts, [0.0, 1.0, 0.0], 4.0);
        assert_eq!(grid.len(), 3);
        for (i, row) in grid.iter().enumerate() {
            assert_eq!(row.len(), 2, "row {i} should have 2 entries");
            vec_near(row[0], pts[i]);
            vec_near(row[1], [pts[i][0], pts[i][1] + 4.0, pts[i][2]]);
        }
    }

    #[test]
    fn extrude_curve_zero_length() {
        let pts = vec![[1.0, 2.0, 3.0]];
        let grid = extrude_curve(&pts, [0.0, 0.0, 1.0], 0.0);
        vec_near(grid[0][0], [1.0, 2.0, 3.0]);
        vec_near(grid[0][1], [1.0, 2.0, 3.0]);
    }
}
