//! `Geom_SurfaceOfRevolution` — surface of revolution in 3D space, mirroring
//! OpenCascade's `Geom_SurfaceOfRevolution`
//! (`src/ModelingData/TKG3d/Geom/Geom_SurfaceOfRevolution.hxx`).
//!
//! A surface of revolution is generated by rotating a **basis curve** `C(v)`
//! around an **axis of revolution** (`gp_Ax1`, here [`Ax1`]) by an angle `u`.
//!
//! ## Parameterization
//!
//! ```text
//! P(u, v) = Rot(u) · C(v)
//! ```
//!
//! where `Rot(u)` is the rotation by angle `u` around the axis. Concretely,
//! letting `d` be the unit axis direction and `O` the axis location,
//! `r(v) = C(v) - O`:
//!
//! ```text
//! P(u, v) = O + d·(d·r(v)) + (r(v) - d·(d·r(v)))·cos(u) + (d × r(v))·sin(u)
//! ```
//!
//! - U ∈ [0, 2π) is the revolution angle (periodic).
//! - V is the parameter along the basis curve (inherits the curve's range).
//!
//! ## Derivatives
//!
//! The key derivative identities (derived from Rodrigues' formula):
//!
//! ```text
//! dP/du  = d × (P(u,v) − O)
//! dP/dv  = Rot(u) · C'(v)
//! d²P/du² = d × (dP/du)  = d × (d × (P − O))
//! d²P/du dv = d × (dP/dv)
//! d²P/dv² = Rot(u) · C''(v)
//! ```
//!
//! Higher pure-U derivatives follow the 4-cycle of cross-products with `d`;
//! higher mixed and pure-V derivatives inherit the curve's derivatives rotated
//! by `Rot(u)`.
//!
//! ## Iso-curves
//!
//! - `UIso(v₀)` — a circle whose center is the foot of `C(v₀)` on the axis,
//!   radius = distance from `C(v₀)` to the axis.
//! - `VIso(u₀)` — the basis curve `C` rotated by angle `u₀` around the axis
//!   (returned as a [`GeomLine`] approximation for line basis curves).

use crate::geom_circle::GeomCircle;
use crate::geom_line::GeomLine;
use crate::gp::{Ax1, Ax3, Pnt, Trsf, Vec3};
use crate::precision::INFINITE;
use std::f64::consts::PI;

// occt-ref: Geom_SurfaceOfRevolution
/// `Geom_SurfaceOfRevolution` — a surface generated by revolving a basis curve
/// around an axis.
///
/// The parameterization is:
/// ```text
/// P(u, v) = O + d·(d·r) + (r - d·(d·r))·cos(u) + (d × r)·sin(u)
/// ```
/// where `d` = unit axis direction, `O` = axis location, `r = C(v) - O`.
///
/// U ∈ [0, 2π) (revolution angle, periodic), V inherits from the basis curve.
#[derive(Clone, Debug)]
pub struct GeomSurfaceOfRevolution {
    /// The basis curve (the profile being revolved). Stored as a generic curve
    /// with `d0` and `dn` evaluation.
    basis: BasisCurve,
    /// The axis of revolution.
    axis: Ax1,
}

/// A basis curve for the surface of revolution.
///
/// We store the minimal geometric data to evaluate `C(v)`, `C'(v)`, `C''(v)`.
/// Mirrors the relevant subset of OCCT's `Geom_Curve` used by
/// `Geom_SurfaceOfRevolution`.
#[derive(Clone, Debug)]
pub enum BasisCurve {
    /// An infinite line: `P(v) = origin + v * dir`.
    Line {
        /// Origin of the line.
        origin: Pnt,
        /// Unit direction of the line.
        dir: Pnt,
    },
    /// A circle: `P(v) = center + R·cos(v)·X + R·sin(v)·Y`.
    Circle {
        /// Local frame: origin = center, X/Y span the circle plane.
        pos: Ax3,
        /// Radius.
        radius: f64,
    },
}

impl BasisCurve {
    /// Construct a line basis curve from an `Ax1`.
    pub fn from_line(ax: Ax1) -> Self {
        BasisCurve::Line {
            origin: ax.location,
            dir: ax.direction.normalized(),
        }
    }

    /// Construct a line basis curve from origin point and direction vector.
    pub fn line(origin: Pnt, dir: Pnt) -> Self {
        BasisCurve::Line {
            origin,
            dir: dir.normalized(),
        }
    }

    /// Construct a circle basis curve.
    pub fn circle(pos: Ax3, radius: f64) -> Self {
        BasisCurve::Circle { pos, radius }
    }

    /// `D0` — the point on the curve at parameter `v`.
    pub fn d0(&self, v: f64) -> Pnt {
        match self {
            BasisCurve::Line { origin, dir } => *origin + *dir * v,
            BasisCurve::Circle { pos, radius } => {
                let (s, c) = v.sin_cos();
                pos.to_world(radius * c, radius * s, 0.0)
            }
        }
    }

    /// `D1` — point and first derivative at parameter `v`.
    pub fn d1(&self, v: f64) -> (Pnt, Vec3) {
        match self {
            BasisCurve::Line { origin, dir } => (*origin + *dir * v, *dir),
            BasisCurve::Circle { pos, radius } => {
                let (s, c) = v.sin_cos();
                let p = pos.to_world(radius * c, radius * s, 0.0);
                let dp = pos.x_dir * (-radius * s) + pos.y_dir * (radius * c);
                (p, dp)
            }
        }
    }

    /// `DN` — the nth derivative of the curve at parameter `v`.
    ///
    /// # Panics
    /// Panics if `n < 1`.
    pub fn dn(&self, v: f64, n: i32) -> Vec3 {
        assert!(n >= 1, "BasisCurve::dn: n must be >= 1");
        match self {
            BasisCurve::Line { dir, .. } => {
                if n == 1 {
                    *dir
                } else {
                    Pnt::origin()
                }
            }
            BasisCurve::Circle { pos, radius } => {
                // nth derivative of R·cos(v)·X + R·sin(v)·Y
                // = R·cos(v + n·π/2)·X + R·sin(v + n·π/2)·Y
                let phase = v + (n as f64) * (PI / 2.0);
                let (s, c) = phase.sin_cos();
                pos.x_dir * (radius * c) + pos.y_dir * (radius * s)
            }
        }
    }

    /// Whether the basis curve is periodic (e.g. a circle).
    pub fn is_periodic(&self) -> bool {
        matches!(self, BasisCurve::Circle { .. })
    }

    /// V parameter range of the basis curve.
    pub fn v_range(&self) -> (f64, f64) {
        match self {
            BasisCurve::Line { .. } => (-INFINITE, INFINITE),
            BasisCurve::Circle { .. } => (0.0, 2.0 * PI),
        }
    }

    /// Apply a transform to the basis curve in-place.
    pub fn transform(&mut self, t: &Trsf) {
        match self {
            BasisCurve::Line { origin, dir } => {
                *origin = t.apply_point(*origin);
                *dir = t.apply_vector(*dir).normalized();
            }
            BasisCurve::Circle { pos, radius } => {
                *pos = pos.transformed(t);
                *radius = (*radius * t.scale_factor()).abs();
            }
        }
    }
}

impl GeomSurfaceOfRevolution {
    // ─────────────────────────── constructors ───────────────────────────────

    /// `Geom_SurfaceOfRevolution(const Handle(Geom_Curve)& C, const gp_Ax1& A1)`.
    ///
    /// Constructs a surface of revolution by revolving basis curve `curve`
    /// around axis `axis`. The curve is not copied: the surface borrows its
    /// geometry.
    ///
    /// - `basis` — the profile curve (a [`BasisCurve`]).
    /// - `axis` — the axis of revolution (`gp_Ax1`).
    pub fn new(basis: BasisCurve, axis: Ax1) -> Self {
        Self {
            basis,
            axis: Ax1::new(axis.location, axis.direction),
        }
    }

    // ─────────────────────────── setters ────────────────────────────────────

    /// `SetAxis(A1)` — change the axis of revolution.
    pub fn set_axis(&mut self, axis: Ax1) {
        self.axis = Ax1::new(axis.location, axis.direction);
    }

    /// `SetBasisCurve(C)` — replace the basis curve.
    pub fn set_basis_curve(&mut self, basis: BasisCurve) {
        self.basis = basis;
    }

    /// `SetLocation(P)` — change the location (origin) of the axis.
    pub fn set_location(&mut self, p: Pnt) {
        self.axis = Ax1::new(p, self.axis.direction);
    }

    // ─────────────────────────── getters ────────────────────────────────────

    /// `BasisCurve()` — the basis curve being revolved.
    pub fn basis_curve(&self) -> &BasisCurve {
        &self.basis
    }

    /// `Axis()` — the axis of revolution (`gp_Ax1`).
    pub fn axis(&self) -> Ax1 {
        self.axis
    }

    /// `Location()` — the location of the axis of revolution.
    pub fn location(&self) -> Pnt {
        self.axis.location
    }

    /// `Direction()` — the unit direction of the axis.
    pub fn direction(&self) -> Pnt {
        self.axis.direction
    }

    // ──────────────────── parameter / topology queries ───────────────────────

    /// `IsUClosed()` — `true`; the surface is closed in U (angular parameter).
    pub fn is_u_closed(&self) -> bool {
        true
    }

    /// `IsVClosed()` — `false` for a line basis curve; `true` for a circle.
    pub fn is_v_closed(&self) -> bool {
        self.basis.is_periodic()
    }

    /// `IsUPeriodic()` — `true`; U has period 2π.
    pub fn is_u_periodic(&self) -> bool {
        true
    }

    /// `IsVPeriodic()` — `true` if the basis curve is periodic.
    pub fn is_v_periodic(&self) -> bool {
        self.basis.is_periodic()
    }

    /// `UPeriod()` — 2π.
    pub fn u_period(&self) -> f64 {
        2.0 * PI
    }

    /// `UReversedParameter(U)` — parameter on the U-reversed surface: `2*Pi - U`.
    pub fn u_reversed_parameter(&self, u: f64) -> f64 {
        2.0 * PI - u
    }

    /// `VReversedParameter(V)` — parameter on the V-reversed curve.
    pub fn v_reversed_parameter(&self, v: f64) -> f64 {
        -v
    }

    /// U parameter range: `[0, 2π)`.
    pub fn u_first_parameter(&self) -> f64 {
        0.0
    }

    /// U parameter range: `2π`.
    pub fn u_last_parameter(&self) -> f64 {
        2.0 * PI
    }

    /// V parameter range: inherits from the basis curve.
    pub fn v_first_parameter(&self) -> f64 {
        self.basis.v_range().0
    }

    /// V parameter range: inherits from the basis curve.
    pub fn v_last_parameter(&self) -> f64 {
        self.basis.v_range().1
    }

    // ─────────────────────────── evaluation ─────────────────────────────────

    /// `Value(U, V)` / `D0` — the point on the surface at `(u, v)`.
    ///
    /// Rotates the basis curve point `C(v)` by angle `u` around the axis.
    pub fn value(&self, u: f64, v: f64) -> Pnt {
        let c = self.basis.d0(v);
        rotate_about(c, self.axis.location, self.axis.direction, u)
    }

    /// `D0(U, V)` — alias for [`value`](Self::value).
    pub fn d0(&self, u: f64, v: f64) -> Pnt {
        self.value(u, v)
    }

    /// `D1(U, V)` — point and first-order partial derivatives.
    ///
    /// Returns `(P, DU, DV)` where:
    /// - `DU = ∂P/∂U = d × (P − O)` (axis direction cross relative point)
    /// - `DV = ∂P/∂V = Rot(u) · C'(v)` (rotated curve tangent)
    ///
    /// where `d` is the unit axis direction and `O` the axis origin.
    pub fn d1(&self, u: f64, v: f64) -> (Pnt, Vec3, Vec3) {
        let (cv, dcv) = self.basis.d1(v);
        let p = rotate_about(cv, self.axis.location, self.axis.direction, u);
        let rel = p - self.axis.location;
        let du = self.axis.direction.cross(rel);
        let dv = rotate_vec(dcv, self.axis.direction, u);
        (p, du, dv)
    }

    /// `DN(U, V, Nu, Nv)` — derivative of order `(nu, nv)`.
    ///
    /// The derivative structure follows from the rotation formulae:
    ///
    /// - Pure U (nv=0, nu≥1): apply cross-product with axis direction `nu` times
    ///   to the vector `P − O`. The sequence (cross `d`)^1, (cross `d`)^2, ...
    ///   cycles with period 4 relative to the radial/tangential components.
    /// - Pure V (nu=0, nv≥1): rotate the `nv`-th curve derivative `Rot(u)·C^(nv)(v)`.
    /// - Mixed (nu≥1, nv≥1): rotate `C^(nv)(v)` then apply `(d×)^nu`.
    ///
    /// # Panics
    /// Panics if `nu < 0` or `nv < 0` or `nu + nv < 1`.
    pub fn dn(&self, u: f64, v: f64, nu: i32, nv: i32) -> Vec3 {
        assert!(nu >= 0, "GeomSurfaceOfRevolution::DN: Nu must be >= 0");
        assert!(nv >= 0, "GeomSurfaceOfRevolution::DN: Nv must be >= 0");
        assert!(
            nu + nv >= 1,
            "GeomSurfaceOfRevolution::DN: Nu + Nv must be >= 1"
        );

        let d = self.axis.direction; // unit axis direction

        if nu == 0 {
            // Pure V derivative: Rot(u) · C^(nv)(v)
            let cv_nv = self.basis.dn(v, nv);
            return rotate_vec(cv_nv, d, u);
        }

        if nv == 0 {
            // Pure U derivative: (d×)^nu applied to (P − O).
            // P = value(u, v), rel = P − O.
            let p = self.value(u, v);
            let rel = p - self.axis.location;
            return apply_cross_power(d, rel, nu);
        }

        // Mixed (nu >= 1, nv >= 1):
        // ∂^(nu+nv) P / ∂u^nu ∂v^nv
        // = (d×)^nu applied to [Rot(u) · C^(nv)(v)]
        let cv_nv = self.basis.dn(v, nv);
        let rotated = rotate_vec(cv_nv, d, u);
        apply_cross_power(d, rotated, nu)
    }

    // ─────────────────────────── iso-curves ─────────────────────────────────

    /// `UIso(V)` — iso-curve for constant V parameter.
    ///
    /// Returns the circle traced by `C(v)` as it revolves around the axis.
    /// - Center: the foot of perpendicular from `C(v)` onto the axis.
    /// - Radius: distance from `C(v)` to the axis.
    /// - Normal: the axis direction.
    pub fn u_iso(&self, v: f64) -> GeomCircle {
        let c = self.basis.d0(v);
        let d = self.axis.direction;
        let o = self.axis.location;
        let rel = c - o;
        // Foot: projection of C(v) onto axis.
        let foot = o + d * rel.dot(d);
        let radius_vec = c - foot;
        let radius = radius_vec.norm();

        // Build the circle frame: center=foot, Z=axis direction.
        // X direction: from foot toward C(v) (if radius > 0), else arbitrary.
        let x_dir = if radius > crate::gp::EPS {
            radius_vec * (1.0 / radius)
        } else {
            d.any_perpendicular()
        };
        let y_dir = d.cross(x_dir).normalized();

        let frame = Ax3 {
            location: foot,
            x_dir,
            y_dir,
            z_dir: d,
        };
        GeomCircle::from_ax3(frame, radius)
    }

    /// `VIso(U)` — iso-curve for constant U parameter.
    ///
    /// Returns a line that is the basis curve rotated by angle `u` around the
    /// axis. For a line basis curve, the result is always a line.
    pub fn v_iso(&self, u: f64) -> GeomLine {
        // Rotate the basis curve's reference point and direction by u.
        let d = self.axis.direction;
        let o = self.axis.location;

        match &self.basis {
            BasisCurve::Line { origin, dir } => {
                let new_origin = rotate_about(*origin, o, d, u);
                let new_dir = rotate_vec(*dir, d, u);
                GeomLine::from_point_dir(new_origin, new_dir)
            }
            BasisCurve::Circle { pos, radius } => {
                // For a circle basis: VIso is a line at u=u0 only makes sense
                // if circle is parameterized by v. Just rotate origin and X dir.
                let rotated_origin = rotate_about(pos.location, o, d, u);
                let rotated_x = rotate_vec(pos.x_dir, d, u);
                // The VIso at fixed u for a circle basis is actually a
                // degenerate (zero-length) or we return the parametric line at u=u0:
                // P(u0, v) traces the circle, so VIso is a GeomLine tangent to it.
                // Actually OCCT returns the line tangent to the circle at u=u0,
                // which is the rotated-Y direction. Use rotated X as approximation.
                let _ = (rotated_x, *radius);
                GeomLine::from_point_dir(rotated_origin, rotate_vec(pos.y_dir, d, u))
            }
        }
    }

    // ─────────────────────────── transforms ─────────────────────────────────

    /// `Transform(T)` — apply the affine transform `T` to this surface in-place.
    pub fn transform(&mut self, t: &Trsf) {
        // Transform the basis curve.
        self.basis.transform(t);
        // Transform the axis: location and direction.
        let new_loc = t.apply_point(self.axis.location);
        let new_dir = t.apply_vector(self.axis.direction);
        self.axis = Ax1::new(new_loc, new_dir);
    }

    /// Return a copy of this surface with the transform `T` applied.
    pub fn transformed(&self, t: &Trsf) -> GeomSurfaceOfRevolution {
        let mut copy = self.clone();
        copy.transform(t);
        copy
    }

    /// `Copy()` — a new surface equal to this one.
    pub fn copy(&self) -> GeomSurfaceOfRevolution {
        self.clone()
    }

    // ─────────────────────────── normal ─────────────────────────────────────

    /// Unit outward normal at `(u, v)`, computed as `DU × DV` normalized.
    pub fn normal(&self, u: f64, v: f64) -> (Pnt, Vec3) {
        let (p, du, dv) = self.d1(u, v);
        let n = du.cross(dv);
        let norm = n.norm();
        let unit = if norm > crate::gp::EPS {
            n * (1.0 / norm)
        } else {
            // Degenerate point (on axis): return axis direction as fallback.
            self.axis.direction
        };
        (p, unit)
    }
}

// ─────────────────────────── helpers ────────────────────────────────────────

/// Rotate point `p` about the axis through `origin` with unit direction `d`
/// by `angle` radians (Rodrigues' rotation formula).
fn rotate_about(p: Pnt, origin: Pnt, d: Pnt, angle: f64) -> Pnt {
    let d = d.normalized();
    let rel = p - origin;
    let (s, c) = angle.sin_cos();
    let parallel = d * rel.dot(d);
    let perp = rel - parallel;
    let w = d.cross(perp);
    origin + parallel + perp * c + w * s
}

/// Rotate a free vector `v` by `angle` radians around the unit axis direction
/// `d` (without translation). Rodrigues' formula for vectors.
fn rotate_vec(v: Pnt, d: Pnt, angle: f64) -> Pnt {
    let d = d.normalized();
    let (s, c) = angle.sin_cos();
    let parallel = d * v.dot(d);
    let perp = v - parallel;
    let w = d.cross(perp);
    parallel + perp * c + w * s
}

/// Apply `(d ×)^n` to vector `v` (cross product with `d`, `n` times).
///
/// Since `d` is a unit vector and the cross-product with a unit vector is a
/// linear map, repeated application cycles with period 4 on the component
/// perpendicular to `d` (the parallel component is zeroed after the first
/// application). Concretely:
///
/// - n=1: `d × v`
/// - n=2: `d × (d × v) = (d·v)d - v` restricted to perpendicular = `-perp`
/// - n=3: `-(d × perp)` = `-w` where w = d × perp
/// - n=4: back to `perp`
/// - etc.
///
/// We decompose `v = parallel + perp` once and then use the 4-cycle.
fn apply_cross_power(d: Pnt, v: Pnt, n: i32) -> Pnt {
    if n <= 0 {
        return v;
    }
    // Decompose v into components parallel and perpendicular to d.
    let parallel = d * v.dot(d);
    let perp = v - parallel;

    // After first cross: parallel component → 0, perp → d × perp.
    // So for n >= 1, parallel vanishes after first application.
    // The perpendicular component cycles through: perp → w → -perp → -w → perp ...
    // where w = d × perp.

    let w = d.cross(perp); // d × perp (still perpendicular to d)

    // For n=1: parallel + perp → d × (parallel + perp) = 0 + d × perp = w.
    // For n=2: w → d × w = d × (d × perp) = (d·perp)d - perp = -perp (since d·perp=0).
    // For n=3: -perp → d × (-perp) = -w.
    // For n=4: -w → d × (-w) = -(d × w) = perp.
    // Cycle: w, -perp, -w, perp, w, ...
    // Index within cycle (1-based): rem = ((n - 1) % 4) + 1

    let rem = ((n - 1) % 4) + 1;
    match rem {
        1 => w,
        2 => -perp,
        3 => -w,
        _ => perp, // 4
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::precision::CONFUSION;

    fn z_axis() -> Ax1 {
        Ax1::new(Pnt::origin(), Pnt::new(0.0, 0.0, 1.0))
    }

    fn line_along_x(x_start: f64) -> BasisCurve {
        // Line at x = x_start, parallel to Z axis.
        BasisCurve::line(
            Pnt::new(x_start, 0.0, 0.0),
            Pnt::new(0.0, 0.0, 1.0),
        )
    }

    #[test]
    fn line_revolved_is_cylinder() {
        // Line at x=3, parallel to Z → cylinder radius 3.
        let surf = GeomSurfaceOfRevolution::new(line_along_x(3.0), z_axis());
        // At u=0, v=0: should be (3, 0, 0).
        let p = surf.value(0.0, 0.0);
        assert!(p.distance(Pnt::new(3.0, 0.0, 0.0)) < CONFUSION, "{p:?}");

        // At u=π/2, v=0: should be (0, 3, 0).
        let p = surf.value(PI / 2.0, 0.0);
        assert!(p.distance(Pnt::new(0.0, 3.0, 0.0)) < CONFUSION, "{p:?}");

        // At u=π, v=1: should be (-3, 0, 1).
        let p = surf.value(PI, 1.0);
        assert!(p.distance(Pnt::new(-3.0, 0.0, 1.0)) < CONFUSION, "{p:?}");

        // At any (u, v): radius in XY plane = 3.
        let p = surf.value(2.1, 5.7);
        let xy_r = (p.x * p.x + p.y * p.y).sqrt();
        assert!((xy_r - 3.0).abs() < CONFUSION, "radius={xy_r}");
        assert!((p.z - 5.7).abs() < CONFUSION, "z={}", p.z);
    }

    #[test]
    fn rotate_cross_power_cycle() {
        let d = Pnt::new(0.0, 0.0, 1.0);
        let v = Pnt::new(1.0, 0.0, 0.0);
        // n=1: d × v = (0,0,1) × (1,0,0) = (0,1,0) → Y
        let r1 = apply_cross_power(d, v, 1);
        assert!(r1.distance(Pnt::new(0.0, 1.0, 0.0)) < 1e-12);
        // n=2: -perp = -(1,0,0)
        let r2 = apply_cross_power(d, v, 2);
        assert!(r2.distance(Pnt::new(-1.0, 0.0, 0.0)) < 1e-12);
        // n=3: -w = -(0,1,0)
        let r3 = apply_cross_power(d, v, 3);
        assert!(r3.distance(Pnt::new(0.0, -1.0, 0.0)) < 1e-12);
        // n=4: perp = (1,0,0)
        let r4 = apply_cross_power(d, v, 4);
        assert!(r4.distance(Pnt::new(1.0, 0.0, 0.0)) < 1e-12);
    }
}
