// FILE: geom_sweep_surface.rs
//! `Geom_SweptSurface` — base and concrete swept-surface types, mirroring
//! OpenCascade's `Geom_SweptSurface` hierarchy from TKG3d.
//!
//! ## Hierarchy
//!
//! ```text
//! Geom_Surface
//!   └─ Geom_SweptSurface            (abstract in OCCT — here: GeomSweptSurface enum)
//!         ├─ Geom_SurfaceOfLinearExtrusion  → re-exported from geom_extrusion_surface
//!         └─ Geom_SurfaceOfRevolution       → re-exported from geom_revol_surface
//! ```
//!
//! ### Geom_SweptSurface
//! The abstract base stores the **basis curve** and the **direction** (for
//! extrusion) or **axis** (for revolution).  In Rust we model this as an
//! owning enum `GeomSweptSurface` whose variants carry the two concrete types.
//!
//! ### Geom_SurfaceOfLinearExtrusion
//! `P(U, V) = C(U) + V * Direction` — already implemented fully in
//! `geom_extrusion_surface`.  Re-exported here for the combined API.
//!
//! ### Geom_SurfaceOfRevolution
//! `P(U, V) = Rot(U, axis) · C(V)` — already implemented fully in
//! `geom_revol_surface`.  Re-exported here for the combined API.
//!
//! This module adds:
//! - `GeomSweptSurface` — the unified dispatch enum.
//! - `SweptSurfaceKind` — a lightweight tag enum.
//! - Convenience constructors and a uniform surface evaluation API.

use crate::geom_extrusion_surface::{GeomCurve, GeomSurfaceOfLinearExtrusion};
use crate::geom_revol_surface::{BasisCurve, GeomSurfaceOfRevolution};
use crate::gp::{Ax1, Ax3, Pnt, Trsf, Vec3};
use crate::geom_circle::GeomCircle;
use crate::geom_line::GeomLine;
use crate::precision::INFINITE;
use std::f64::consts::PI;

// Re-export the two concrete types so consumers can `use geom_sweep_surface::*`.
pub use crate::geom_extrusion_surface::GeomSurfaceOfLinearExtrusion as SurfaceOfLinearExtrusion;
pub use crate::geom_revol_surface::GeomSurfaceOfRevolution as SurfaceOfRevolution;
pub use crate::geom_extrusion_surface::GeomCurve as ExtrusionBasisCurve;
pub use crate::geom_revol_surface::BasisCurve as RevolutionBasisCurve;

// ─────────────────────────── SweptSurfaceKind ───────────────────────────────

/// Tag identifying the kind of a swept surface.
///
/// Mirrors `STANDARD_TYPE` queries in OCCT that distinguish the two concrete
/// subclasses of `Geom_SweptSurface`.
// occt: Geom_SweptSurface (kind tag)
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SweptSurfaceKind {
    /// `Geom_SurfaceOfLinearExtrusion` — linear sweep (prism).
    LinearExtrusion,
    /// `Geom_SurfaceOfRevolution` — rotational sweep.
    Revolution,
}

// ─────────────────────────── GeomSweptSurface ───────────────────────────────

/// `Geom_SweptSurface` — a surface generated by sweeping a basis curve.
///
/// This Rust enum models the abstract base class from OCCT's TKG3d. Both
/// concrete variants share:
///
/// - A **basis curve** (the profile being swept).
/// - A **sweep direction** — either a linear direction vector (`Extrusion`)
///   or a rotational axis (`Revolution`).
///
/// The enum dispatches `value`, `d0`, `d1`, `dn`, `u_iso`, `v_iso` and
/// topology queries uniformly to the appropriate concrete implementation.
// occt: Geom_SweptSurface
#[derive(Clone, Debug)]
pub enum GeomSweptSurface {
    /// `Geom_SurfaceOfLinearExtrusion` variant.
    Extrusion(GeomSurfaceOfLinearExtrusion),
    /// `Geom_SurfaceOfRevolution` variant.
    Revolution(GeomSurfaceOfRevolution),
}

impl GeomSweptSurface {
    // ────────────────────────── constructors ─────────────────────────────────

    /// Build a linear-extrusion swept surface.
    ///
    /// Mirrors `Geom_SurfaceOfLinearExtrusion(C, V)`.
    pub fn new_extrusion(basis: GeomCurve, direction: Vec3) -> Self {
        GeomSweptSurface::Extrusion(GeomSurfaceOfLinearExtrusion::new(basis, direction))
    }

    /// Build a revolution swept surface.
    ///
    /// Mirrors `Geom_SurfaceOfRevolution(C, Ax1)`.
    pub fn new_revolution(basis: BasisCurve, axis: Ax1) -> Self {
        GeomSweptSurface::Revolution(GeomSurfaceOfRevolution::new(basis, axis))
    }

    // ─────────────────────────── kind ────────────────────────────────────────

    /// Return the [`SweptSurfaceKind`] tag for this surface.
    pub fn kind(&self) -> SweptSurfaceKind {
        match self {
            GeomSweptSurface::Extrusion(_) => SweptSurfaceKind::LinearExtrusion,
            GeomSweptSurface::Revolution(_) => SweptSurfaceKind::Revolution,
        }
    }

    /// Whether this is an extrusion surface.
    pub fn is_extrusion(&self) -> bool {
        matches!(self, GeomSweptSurface::Extrusion(_))
    }

    /// Whether this is a revolution surface.
    pub fn is_revolution(&self) -> bool {
        matches!(self, GeomSweptSurface::Revolution(_))
    }

    // ─────────────────────── parameter queries ────────────────────────────────

    /// First U parameter of the surface.
    pub fn u_first_parameter(&self) -> f64 {
        match self {
            GeomSweptSurface::Extrusion(s) => s.u_first_parameter(),
            GeomSweptSurface::Revolution(s) => s.u_first_parameter(),
        }
    }

    /// Last U parameter of the surface.
    pub fn u_last_parameter(&self) -> f64 {
        match self {
            GeomSweptSurface::Extrusion(s) => s.u_last_parameter(),
            GeomSweptSurface::Revolution(s) => s.u_last_parameter(),
        }
    }

    /// First V parameter of the surface.
    pub fn v_first_parameter(&self) -> f64 {
        match self {
            GeomSweptSurface::Extrusion(s) => s.v_first_parameter(),
            GeomSweptSurface::Revolution(s) => s.v_first_parameter(),
        }
    }

    /// Last V parameter of the surface.
    pub fn v_last_parameter(&self) -> f64 {
        match self {
            GeomSweptSurface::Extrusion(s) => s.v_last_parameter(),
            GeomSweptSurface::Revolution(s) => s.v_last_parameter(),
        }
    }

    // ─────────────────── topology flags (OCCT virtual interface) ─────────────

    /// `IsUClosed` — whether the surface is closed in U.
    pub fn is_u_closed(&self) -> bool {
        match self {
            GeomSweptSurface::Extrusion(s) => s.is_u_closed(),
            GeomSweptSurface::Revolution(s) => s.is_u_closed(),
        }
    }

    /// `IsVClosed` — whether the surface is closed in V.
    pub fn is_v_closed(&self) -> bool {
        match self {
            GeomSweptSurface::Extrusion(s) => s.is_v_closed(),
            GeomSweptSurface::Revolution(s) => s.is_v_closed(),
        }
    }

    /// `IsUPeriodic` — whether the U parameter is periodic.
    pub fn is_u_periodic(&self) -> bool {
        match self {
            GeomSweptSurface::Extrusion(s) => s.is_u_periodic(),
            GeomSweptSurface::Revolution(s) => s.is_u_periodic(),
        }
    }

    /// `IsVPeriodic` — whether the V parameter is periodic.
    pub fn is_v_periodic(&self) -> bool {
        match self {
            GeomSweptSurface::Extrusion(s) => s.is_v_periodic(),
            GeomSweptSurface::Revolution(s) => s.is_v_periodic(),
        }
    }

    // ───────────────────────── evaluation ────────────────────────────────────

    /// `D0(U, V)` / `Value(U, V)` — the point on the surface.
    pub fn value(&self, u: f64, v: f64) -> Pnt {
        match self {
            GeomSweptSurface::Extrusion(s) => s.value(u, v),
            GeomSweptSurface::Revolution(s) => s.value(u, v),
        }
    }

    /// `D0(U, V)` — alias for [`value`](Self::value).
    pub fn d0(&self, u: f64, v: f64) -> Pnt {
        self.value(u, v)
    }

    /// `D1(U, V)` — point and first-order partial derivatives `(P, DU, DV)`.
    pub fn d1(&self, u: f64, v: f64) -> (Pnt, Vec3, Vec3) {
        match self {
            GeomSweptSurface::Extrusion(s) => s.d1(u, v),
            GeomSweptSurface::Revolution(s) => s.d1(u, v),
        }
    }

    /// `DN(U, V, Nu, Nv)` — partial derivative of order `(Nu, Nv)`.
    ///
    /// # Panics
    /// Panics if `nu < 0`, `nv < 0`, or `nu + nv < 1`.
    pub fn dn(&self, u: f64, v: f64, nu: i32, nv: i32) -> Vec3 {
        match self {
            GeomSweptSurface::Extrusion(s) => s.dn(u, v, nu, nv),
            GeomSweptSurface::Revolution(s) => s.dn(u, v, nu, nv),
        }
    }

    // ───────────────────────── iso curves ────────────────────────────────────

    /// `UIso` — iso-curve at constant U as a line.
    ///
    /// For extrusion: a ruling line through `C(U)` along the extrusion direction.
    /// For revolution: not a simple line in general; returns the line approximation
    /// of the rotated basis curve tangent at `U` (the VIso of the revolution at `u`).
    pub fn u_iso_line(&self, u: f64) -> GeomLine {
        match self {
            GeomSweptSurface::Extrusion(s) => s.u_iso(u),
            GeomSweptSurface::Revolution(s) => s.v_iso(u),
        }
    }

    /// `UIso` as a circle — only valid for revolution surfaces (the U-iso of a
    /// revolution is a circle).
    ///
    /// Returns `Some(circle)` for a revolution surface, `None` for extrusion.
    pub fn u_iso_circle(&self, v: f64) -> Option<GeomCircle> {
        match self {
            GeomSweptSurface::Extrusion(_) => None,
            GeomSweptSurface::Revolution(s) => Some(s.u_iso(v)),
        }
    }

    // ─────────────────────────── transforms ──────────────────────────────────

    /// `Transform(T)` — apply an affine transform in-place.
    pub fn transform(&mut self, t: &Trsf) {
        match self {
            GeomSweptSurface::Extrusion(s) => s.transform(t),
            GeomSweptSurface::Revolution(s) => s.transform(t),
        }
    }

    /// Return a transformed copy.
    pub fn transformed(&self, t: &Trsf) -> GeomSweptSurface {
        let mut copy = self.clone();
        copy.transform(t);
        copy
    }

    /// `Copy()` — a deep clone.
    pub fn copy(&self) -> GeomSweptSurface {
        self.clone()
    }

    // ─────────────────────────── normal ──────────────────────────────────────

    /// Unit outward surface normal at `(u, v)` — computed as `DU × DV` normalized.
    ///
    /// Returns `(point, normal)`.
    pub fn normal(&self, u: f64, v: f64) -> (Pnt, Vec3) {
        let (p, du, dv) = self.d1(u, v);
        let n = du.cross(dv);
        let norm = n.norm();
        let unit = if norm > crate::gp::EPS {
            n * (1.0 / norm)
        } else {
            // Degenerate: return fallback Z direction.
            Pnt::new(0.0, 0.0, 1.0)
        };
        (p, unit)
    }

    // ────────────────────── down-cast helpers ─────────────────────────────────

    /// Borrow the inner extrusion surface, if this is an extrusion variant.
    pub fn as_extrusion(&self) -> Option<&GeomSurfaceOfLinearExtrusion> {
        match self {
            GeomSweptSurface::Extrusion(s) => Some(s),
            _ => None,
        }
    }

    /// Borrow the inner revolution surface, if this is a revolution variant.
    pub fn as_revolution(&self) -> Option<&GeomSurfaceOfRevolution> {
        match self {
            GeomSweptSurface::Revolution(s) => Some(s),
            _ => None,
        }
    }
}

// ─────────────── convenience constructors (stand-alone functions) ────────────

/// Build a cylinder surface (`Geom_SurfaceOfRevolution`) of radius `r` around
/// the Z axis.
///
/// This is the canonical OCCT pattern: revolve a line at distance `r` from
/// the Z axis, parallel to Z, by 2π.
pub fn make_cylinder_revolution(r: f64) -> GeomSurfaceOfRevolution {
    let basis = BasisCurve::line(Pnt::new(r, 0.0, 0.0), Pnt::new(0.0, 0.0, 1.0));
    let axis = Ax1::new(Pnt::origin(), Pnt::new(0.0, 0.0, 1.0));
    GeomSurfaceOfRevolution::new(basis, axis)
}

/// Build a circular-extrusion surface of radius `r`, swept along direction `d`.
///
/// The circle is in the XY plane (identity frame). The extrusion direction is
/// `d` (normalized on construction).
pub fn make_circle_extrusion(r: f64, direction: Vec3) -> GeomSurfaceOfLinearExtrusion {
    let circle = GeomCircle::from_ax3(Ax3::identity(), r);
    GeomSurfaceOfLinearExtrusion::new(GeomCurve::Circle(circle), direction)
}

/// Build a torus-like revolution surface by revolving a circle of radius `minor_r`
/// whose center is at distance `major_r` from the Z axis.
///
/// The circle's center is at `(major_r, 0, 0)`, the circle plane is the XZ plane.
/// Revolving around the Z axis gives a torus.
pub fn make_torus_revolution(major_r: f64, minor_r: f64) -> GeomSurfaceOfRevolution {
    // Circle center offset from Z axis, lying in the XZ plane.
    let center = Pnt::new(major_r, 0.0, 0.0);
    // The circle is in the XZ plane: X direction = +X, Y direction = +Z.
    let pos = Ax3 {
        location: center,
        x_dir: Pnt::new(1.0, 0.0, 0.0),
        y_dir: Pnt::new(0.0, 0.0, 1.0),
        z_dir: Pnt::new(0.0, -1.0, 0.0),
    };
    let basis = BasisCurve::circle(pos, minor_r);
    let axis = Ax1::new(Pnt::origin(), Pnt::new(0.0, 0.0, 1.0));
    GeomSurfaceOfRevolution::new(basis, axis)
}

// ───────────────────────── suppress unused-import lints ─────────────────────
const _PI: f64 = PI;
const _INF: f64 = INFINITE;

// ─────────────────────────────── unit tests ──────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::precision::CONFUSION;

    // ── helpers ───────────────────────────────────────────────────────────────

    fn pnt_close(a: Pnt, b: Pnt, tol: f64) -> bool {
        a.distance(b) < tol
    }

    fn vec_close(a: Pnt, b: Pnt, tol: f64) -> bool {
        (a - b).norm() < tol
    }

    /// Circle extrusion (radius r) swept along +Z.
    fn circle_extrusion_swept(r: f64) -> GeomSweptSurface {
        let circle = GeomCircle::from_ax3(Ax3::identity(), r);
        GeomSweptSurface::new_extrusion(GeomCurve::Circle(circle), Pnt::new(0.0, 0.0, 1.0))
    }

    /// Cylinder revolution (line at x=r, parallel to Z, around Z).
    fn cylinder_revolution_swept(r: f64) -> GeomSweptSurface {
        let basis = BasisCurve::line(Pnt::new(r, 0.0, 0.0), Pnt::new(0.0, 0.0, 1.0));
        let axis = Ax1::new(Pnt::origin(), Pnt::new(0.0, 0.0, 1.0));
        GeomSweptSurface::new_revolution(basis, axis)
    }

    // ── test 1: kind() returns correct tag ────────────────────────────────────
    #[test]
    fn test_kind_tag() {
        let ext = circle_extrusion_swept(3.0);
        let rev = cylinder_revolution_swept(3.0);

        assert_eq!(ext.kind(), SweptSurfaceKind::LinearExtrusion);
        assert_eq!(rev.kind(), SweptSurfaceKind::Revolution);

        assert!(ext.is_extrusion());
        assert!(!ext.is_revolution());
        assert!(rev.is_revolution());
        assert!(!rev.is_extrusion());
    }

    // ── test 2: extrusion value matches expected surface ──────────────────────
    #[test]
    fn test_extrusion_value() {
        let r = 4.0;
        let surf = circle_extrusion_swept(r);

        // P(0, 0) = (R, 0, 0)
        let p = surf.value(0.0, 0.0);
        assert!(pnt_close(p, Pnt::new(r, 0.0, 0.0), CONFUSION));

        // P(π/2, 0) = (0, R, 0)
        let p2 = surf.value(PI / 2.0, 0.0);
        assert!(pnt_close(p2, Pnt::new(0.0, r, 0.0), CONFUSION));

        // P(0, 5) = (R, 0, 5)
        let p3 = surf.value(0.0, 5.0);
        assert!(pnt_close(p3, Pnt::new(r, 0.0, 5.0), CONFUSION));

        // d0 and value agree.
        let pa = surf.d0(1.2, -3.4);
        let pb = surf.value(1.2, -3.4);
        assert!(pnt_close(pa, pb, CONFUSION));
    }

    // ── test 3: revolution value matches expected cylinder ────────────────────
    #[test]
    fn test_revolution_value() {
        let r = 5.0;
        let surf = cylinder_revolution_swept(r);

        // P(0, 0) = (R, 0, 0)
        let p = surf.value(0.0, 0.0);
        assert!(pnt_close(p, Pnt::new(r, 0.0, 0.0), CONFUSION));

        // P(π/2, 0) = (0, R, 0)
        let p2 = surf.value(PI / 2.0, 0.0);
        assert!(pnt_close(p2, Pnt::new(0.0, r, 0.0), CONFUSION));

        // P(π, 2) = (-R, 0, 2) for a cylinder
        let p3 = surf.value(PI, 2.0);
        assert!(pnt_close(p3, Pnt::new(-r, 0.0, 2.0), CONFUSION));
    }

    // ── test 4: d1 derivatives on extrusion ───────────────────────────────────
    #[test]
    fn test_extrusion_d1() {
        let r = 3.0;
        let surf = circle_extrusion_swept(r);

        // At U=0: DU = (0, R, 0), DV = (0, 0, 1)
        let (p, du, dv) = surf.d1(0.0, 0.0);
        assert!(pnt_close(p, Pnt::new(r, 0.0, 0.0), CONFUSION));
        assert!(vec_close(du, Pnt::new(0.0, r, 0.0), CONFUSION));
        assert!(vec_close(dv, Pnt::new(0.0, 0.0, 1.0), CONFUSION));

        // DV is always the extrusion direction
        let (_, _, dv2) = surf.d1(2.0, 3.0);
        assert!(vec_close(dv2, Pnt::new(0.0, 0.0, 1.0), CONFUSION));
    }

    // ── test 5: d1 derivatives on revolution ──────────────────────────────────
    #[test]
    fn test_revolution_d1() {
        let r = 3.0;
        let surf = cylinder_revolution_swept(r);

        // For cylinder: DU = d × (P - O) = Z × (r, 0, 0) = (0, r, 0)
        let (p, du, dv) = surf.d1(0.0, 0.0);
        assert!(pnt_close(p, Pnt::new(r, 0.0, 0.0), CONFUSION));
        assert!(vec_close(du, Pnt::new(0.0, r, 0.0), CONFUSION));
        // DV for line basis is the line direction rotated by U=0: (0,0,1)
        assert!(vec_close(dv, Pnt::new(0.0, 0.0, 1.0), CONFUSION));
    }

    // ── test 6: topology flags ──────────────────────────────────────────────────
    #[test]
    fn test_topology_flags() {
        let ext = circle_extrusion_swept(2.0);
        // Extrusion from circle: closed + periodic in U, open in V.
        assert!(ext.is_u_closed());
        assert!(!ext.is_v_closed());
        assert!(ext.is_u_periodic());
        assert!(!ext.is_v_periodic());

        let rev = cylinder_revolution_swept(2.0);
        // Revolution: always closed + periodic in U; V is line: open, not periodic.
        assert!(rev.is_u_closed());
        assert!(!rev.is_v_closed());
        assert!(rev.is_u_periodic());
        assert!(!rev.is_v_periodic());
    }

    // ── test 7: normal is unit and orthogonal to DU, DV ───────────────────────
    #[test]
    fn test_normal_orthogonality() {
        let ext = circle_extrusion_swept(3.0);
        let (_, n) = ext.normal(0.5, 1.0);
        let (_, du, dv) = ext.d1(0.5, 1.0);
        assert!((n.norm() - 1.0).abs() < 1e-9);
        assert!(n.dot(du).abs() < 1e-9);
        assert!(n.dot(dv).abs() < 1e-9);

        let rev = cylinder_revolution_swept(4.0);
        let (_, nr) = rev.normal(1.0, 2.0);
        let (_, dur, dvr) = rev.d1(1.0, 2.0);
        assert!((nr.norm() - 1.0).abs() < 1e-9);
        assert!(nr.dot(dur).abs() < 1e-9);
        assert!(nr.dot(dvr).abs() < 1e-9);
    }

    // ── test 8: make_cylinder_revolution convenience ────────────────────────────
    #[test]
    fn test_make_cylinder_revolution() {
        let r = 7.0;
        let surf = make_cylinder_revolution(r);

        // Point on surface at angle 0: (r, 0, 0)
        let p = surf.value(0.0, 0.0);
        assert!(pnt_close(p, Pnt::new(r, 0.0, 0.0), CONFUSION));

        // Radius in XY plane is constant
        let p2 = surf.value(1.23, 4.56);
        let xy_r = (p2.x * p2.x + p2.y * p2.y).sqrt();
        assert!((xy_r - r).abs() < CONFUSION);

        // Z coordinate equals V parameter
        assert!((p2.z - 4.56).abs() < CONFUSION);
    }

    // ── test 9: make_circle_extrusion convenience ─────────────────────────────
    #[test]
    fn test_make_circle_extrusion() {
        let r = 3.0;
        let surf = make_circle_extrusion(r, Pnt::new(0.0, 0.0, 1.0));

        // At U=0, V=0: (r, 0, 0)
        let p = surf.value(0.0, 0.0);
        assert!(pnt_close(p, Pnt::new(r, 0.0, 0.0), CONFUSION));

        // At U=0, V=10: (r, 0, 10)
        let p2 = surf.value(0.0, 10.0);
        assert!(pnt_close(p2, Pnt::new(r, 0.0, 10.0), CONFUSION));

        // Direction should be unit Z
        let d = surf.direction();
        assert!(vec_close(d, Pnt::new(0.0, 0.0, 1.0), CONFUSION));
    }

    // ── test 10: transform translation on GeomSweptSurface ──────────────────────
    #[test]
    fn test_transform_translation() {
        let r = 2.0;
        let surf = circle_extrusion_swept(r);
        let t = Trsf::translation(Pnt::new(5.0, 10.0, 15.0));
        let surf2 = surf.transformed(&t);

        // P(0, 0) was (r, 0, 0), now (r+5, 10, 15)
        let p = surf2.value(0.0, 0.0);
        assert!(pnt_close(p, Pnt::new(r + 5.0, 10.0, 15.0), CONFUSION));

        // P(0, 3) was (r, 0, 3), now (r+5, 10, 18)
        let p2 = surf2.value(0.0, 3.0);
        assert!(pnt_close(p2, Pnt::new(r + 5.0, 10.0, 18.0), CONFUSION));
    }

    // ── test 11: as_extrusion / as_revolution down-casts ─────────────────────
    #[test]
    fn test_downcast_helpers() {
        let ext = circle_extrusion_swept(1.0);
        assert!(ext.as_extrusion().is_some());
        assert!(ext.as_revolution().is_none());

        let rev = cylinder_revolution_swept(1.0);
        assert!(rev.as_revolution().is_some());
        assert!(rev.as_extrusion().is_none());
    }

    // ── test 12: make_torus_revolution sanity check ──────────────────────────
    #[test]
    fn test_make_torus_revolution() {
        let major_r = 5.0;
        let minor_r = 2.0;
        let surf = make_torus_revolution(major_r, minor_r);

        // At V=0 (outermost point), U=0: center of circle is (major_r, 0, 0),
        // circle at v=0: center + minor_r * x_dir = (major_r + minor_r, 0, 0).
        let p_v0_u0 = surf.value(0.0, 0.0);
        let expected_r = major_r + minor_r;
        let xy_dist = (p_v0_u0.x * p_v0_u0.x + p_v0_u0.y * p_v0_u0.y).sqrt();
        assert!((xy_dist - expected_r).abs() < CONFUSION, "outermost point xy_dist={xy_dist}");

        // At U=π, the same V=0 gives the point on the other side.
        let p_v0_upi = surf.value(PI, 0.0);
        let xy_dist2 = (p_v0_upi.x * p_v0_upi.x + p_v0_upi.y * p_v0_upi.y).sqrt();
        assert!((xy_dist2 - expected_r).abs() < CONFUSION, "opposite side xy_dist={xy_dist2}");
    }

    // ── test 13: u_iso_circle on revolution, None on extrusion ───────────────
    #[test]
    fn test_u_iso_circle() {
        let rev = cylinder_revolution_swept(3.0);
        let circle_opt = rev.u_iso_circle(0.0);
        assert!(circle_opt.is_some(), "revolution should have a U-iso circle");

        let ext = circle_extrusion_swept(3.0);
        let none_opt = ext.u_iso_circle(0.0);
        assert!(none_opt.is_none(), "extrusion should have no U-iso circle");
    }

    // ── test 14: dn on extrusion (mixed = 0) ──────────────────────────────────
    #[test]
    fn test_dn_extrusion_mixed_zero() {
        let surf = circle_extrusion_swept(2.0);
        let u = 0.8;
        let v = 1.5;

        // Mixed partial (1,1): zero for linear extrusion
        let d11 = surf.dn(u, v, 1, 1);
        assert!(vec_close(d11, Pnt::origin(), CONFUSION));

        // Pure nv=2: zero (V is linear)
        let d02 = surf.dn(u, v, 0, 2);
        assert!(vec_close(d02, Pnt::origin(), CONFUSION));
    }

    // ── test 15: copy is independent ──────────────────────────────────────────
    #[test]
    fn test_copy_independence() {
        let surf = circle_extrusion_swept(2.0);
        let surf_copy = surf.copy();

        let p_orig = surf.value(0.0, 0.0);
        let p_copy = surf_copy.value(0.0, 0.0);
        assert!(pnt_close(p_orig, p_copy, CONFUSION));

        // Transforming the original should not affect the copy.
        let t = Trsf::translation(Pnt::new(100.0, 0.0, 0.0));
        let surf_moved = surf.transformed(&t);

        let p_moved = surf_moved.value(0.0, 0.0);
        let p_copy_after = surf_copy.value(0.0, 0.0);
        assert!(!pnt_close(p_moved, p_copy_after, 1.0));
    }
}
