// FILE: graphic3d_c_structure.rs
// occt: Graphic3d_CStructure

/// Low-level graphic structure interface.
/// This is a simplified Rust port that captures the essential state and behavior
/// of the OCCT Graphic3d_CStructure class.
pub struct Graphic3dCStructure {
    /// Structure id (generated by Graphic3d_GraphicDriver::NewIdentification() during construction)
    id: i32,
    /// Visibility flag - can be used to suppress structure while leaving it in the scene graph
    visible: bool,
    /// Transformation persistence flag
    has_group_transform_persistence: bool,
    /// Flipping options flag
    has_group_flipping: bool,
    /// Flag specifying if structure is marked as culled/not culled
    is_culled: bool,
    /// Check of object's bounding box clipping before drawing
    bnd_box_clip_check: bool,
    /// Whether structure is infinite
    is_infinite: bool,
    /// Whether structure is for highlight
    is_for_highlight: bool,
    /// Whether structure is mutable
    is_mutable: bool,
    /// Whether structure is 2D text
    is_2d_text: bool,
    /// Stick flag - should be set when structure has been added to scene graph
    stick: bool,
    /// Highlight flag
    highlight: bool,
    /// HLR validation flag
    hlr_validation: bool,
}

impl Graphic3dCStructure {
    /// Create a new structure with the given ID.
    pub fn new(id: i32) -> Self {
        Self {
            id,
            visible: true,
            has_group_transform_persistence: false,
            has_group_flipping: false,
            is_culled: false,
            bnd_box_clip_check: true,
            is_infinite: false,
            is_for_highlight: false,
            is_mutable: false,
            is_2d_text: false,
            stick: false,
            highlight: false,
            hlr_validation: false,
        }
    }

    /// Return structure id
    pub fn identification(&self) -> i32 {
        self.id
    }

    /// Return structure visibility flag
    pub fn is_visible(&self) -> bool {
        self.visible
    }

    /// Set visibility flag
    pub fn set_visible(&mut self, visible: bool) {
        self.visible = visible;
    }

    /// Return TRUE if some groups might have transform persistence; FALSE by default.
    pub fn has_group_transform_persistence(&self) -> bool {
        self.has_group_transform_persistence
    }

    /// Set if some groups might have transform persistence.
    pub fn set_group_transform_persistence(&mut self, value: bool) {
        self.has_group_transform_persistence = value;
    }

    /// Return TRUE if some groups might have flipping options; FALSE by default.
    pub fn has_group_flipping(&self) -> bool {
        self.has_group_flipping
    }

    /// Set if some groups might have flipping options.
    pub fn set_group_flipping(&mut self, value: bool) {
        self.has_group_flipping = value;
    }

    /// Returns FALSE if the structure hits the current view volume, otherwise returns TRUE.
    pub fn is_culled(&self) -> bool {
        self.is_culled
    }

    /// Marks structure as culled/not culled
    pub fn set_culled(&mut self, is_culled: bool) {
        self.is_culled = is_culled;
    }

    /// Mark structure as not culled
    pub fn mark_as_not_culled(&mut self) {
        self.is_culled = false;
    }

    /// Returns whether check of object's bounding box clipping is enabled before drawing;
    /// TRUE by default.
    pub fn bnd_box_clip_check(&self) -> bool {
        self.bnd_box_clip_check
    }

    /// Enable/disable check of object's bounding box clipping before drawing.
    pub fn set_bnd_box_clip_check(&mut self, check: bool) {
        self.bnd_box_clip_check = check;
    }

    /// Set whether structure is infinite
    pub fn set_infinite(&mut self, infinite: bool) {
        self.is_infinite = infinite;
    }

    /// Get whether structure is infinite
    pub fn is_infinite(&self) -> bool {
        self.is_infinite
    }

    /// Set whether structure is for highlight
    pub fn set_for_highlight(&mut self, for_highlight: bool) {
        self.is_for_highlight = for_highlight;
    }

    /// Get whether structure is for highlight
    pub fn is_for_highlight(&self) -> bool {
        self.is_for_highlight
    }

    /// Set whether structure is mutable
    pub fn set_mutable(&mut self, mutable: bool) {
        self.is_mutable = mutable;
    }

    /// Get whether structure is mutable
    pub fn is_mutable(&self) -> bool {
        self.is_mutable
    }

    /// Set whether structure is 2D text
    pub fn set_2d_text(&mut self, is_2d_text: bool) {
        self.is_2d_text = is_2d_text;
    }

    /// Get whether structure is 2D text
    pub fn is_2d_text(&self) -> bool {
        self.is_2d_text
    }

    /// Checks if the structure should be included into BVH tree or not.
    pub fn is_always_rendered(&self) -> bool {
        self.is_infinite
            || self.is_for_highlight
            || self.is_mutable
            || self.is_2d_text
            || self.has_group_transform_persistence
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_structure() {
        let s = Graphic3dCStructure::new(42);
        assert_eq!(s.identification(), 42);
        assert!(s.is_visible());
        assert!(!s.is_culled());
        assert!(s.bnd_box_clip_check());
    }

    #[test]
    fn test_visibility() {
        let mut s = Graphic3dCStructure::new(1);
        assert!(s.is_visible());
        s.set_visible(false);
        assert!(!s.is_visible());
    }

    #[test]
    fn test_culling() {
        let mut s = Graphic3dCStructure::new(1);
        assert!(!s.is_culled());
        s.set_culled(true);
        assert!(s.is_culled());
        s.mark_as_not_culled();
        assert!(!s.is_culled());
    }

    #[test]
    fn test_bnd_box_clip_check() {
        let mut s = Graphic3dCStructure::new(1);
        assert!(s.bnd_box_clip_check());
        s.set_bnd_box_clip_check(false);
        assert!(!s.bnd_box_clip_check());
    }

    #[test]
    fn test_is_always_rendered_infinite() {
        let mut s = Graphic3dCStructure::new(1);
        assert!(!s.is_always_rendered());
        s.set_infinite(true);
        assert!(s.is_always_rendered());
    }

    #[test]
    fn test_is_always_rendered_for_highlight() {
        let mut s = Graphic3dCStructure::new(1);
        assert!(!s.is_always_rendered());
        s.set_for_highlight(true);
        assert!(s.is_always_rendered());
    }

    #[test]
    fn test_is_always_rendered_mutable() {
        let mut s = Graphic3dCStructure::new(1);
        assert!(!s.is_always_rendered());
        s.set_mutable(true);
        assert!(s.is_always_rendered());
    }

    #[test]
    fn test_is_always_rendered_2d_text() {
        let mut s = Graphic3dCStructure::new(1);
        assert!(!s.is_always_rendered());
        s.set_2d_text(true);
        assert!(s.is_always_rendered());
    }

    #[test]
    fn test_is_always_rendered_with_transform_persistence() {
        let mut s = Graphic3dCStructure::new(1);
        assert!(!s.is_always_rendered());
        s.set_group_transform_persistence(true);
        assert!(s.is_always_rendered());
    }
}
