// FILE: loc_ope_generated_shape.rs
// occt: LocOpe_GeneratedShape

/// Container for shapes generated by local operations.
pub struct LocOpeGeneratedShape {
    generated_ids: Vec<usize>,
}

impl LocOpeGeneratedShape {
    /// Creates a new generated shape container.
    pub fn new() -> Self {
        LocOpeGeneratedShape {
            generated_ids: Vec::new(),
        }
    }

    /// Adds a generated shape.
    pub fn add(&mut self, _shape_id: usize) {
        // Add shape
    }

    /// Returns the number of generated shapes.
    pub fn nb_shapes(&self) -> usize {
        self.generated_ids.len()
    }

    /// Gets the generated shape at index.
    pub fn shape(&self, _index: usize) -> Option<usize> {
        None
    }
}

impl Default for LocOpeGeneratedShape {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generated_shape_creation() {
        let gen = LocOpeGeneratedShape::new();
        assert_eq!(gen.nb_shapes(), 0);
    }
}
