#!/usr/bin/env python3
"""Regenerate crates/ironstream/tests/occt_suite/main.rs from the files on disk.

Every `tests/occt_suite/occt_*.rs` file becomes a `mod` line in `main.rs`, so
the whole ported OCCT test corpus links as ONE integration-test binary
(`cargo test -p ironstream --test occt_suite`) instead of ~700 separate
binaries that would each statically link the full kernel rlib.

Files listed in parity/suite_exclusions.txt are skipped (kept on disk, not
compiled) and recorded as `// EXCLUDED (<reason>): <mod>` lines so the gap is
visible in the generated file.

Usage:  python3 parity/gen_occt_suite.py
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SUITE = ROOT / "crates" / "ironstream" / "tests" / "occt_suite"
EXCLUSIONS = Path(__file__).resolve().parent / "suite_exclusions.txt"

HEADER = """\
//! Consolidated OCCT unit-test suite.
//!
//! Every `tests/occt_suite/*.rs` file is a submodule of this single
//! integration-test binary, so the whole ported OCCT GoogleTest corpus links
//! ONCE instead of as ~700 separate binaries (each of which would statically
//! link the full kernel rlib and collectively exhaust memory).
//!
//! GENERATED by `parity/gen_occt_suite.py` — do not edit by hand. To exclude
//! a module, add it to `parity/suite_exclusions.txt` with a reason and
//! re-run the script.
#![allow(clippy::all)]
"""


def load_exclusions() -> dict[str, str]:
    out: dict[str, str] = {}
    if EXCLUSIONS.exists():
        for line in EXCLUSIONS.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            name, _, reason = line.partition(" ")
            out[name] = reason.strip() or "excluded"
    return out


def main() -> None:
    exclusions = load_exclusions()
    mods = sorted(p.stem for p in SUITE.glob("*.rs") if p.name != "main.rs")

    unknown = sorted(set(exclusions) - set(mods))
    if unknown:
        raise SystemExit(
            f"suite_exclusions.txt lists modules with no file on disk: {unknown}"
        )

    lines = [HEADER]
    for mod in mods:
        if mod in exclusions:
            lines.append(f"// EXCLUDED ({exclusions[mod]}): {mod}")
        else:
            lines.append(f"mod {mod};")

    (SUITE / "main.rs").write_text("\n".join(lines) + "\n")
    included = len(mods) - len(exclusions)
    print(f"main.rs regenerated: {included} modules included, "
          f"{len(exclusions)} excluded")


if __name__ == "__main__":
    main()
