#!/usr/bin/env python3
"""Regenerate docs/examples.js from the CADbuildr foundation doc examples.

Dev-only helper: reads the canonical example sources from the monorepo's
foundation_ex package, unwraps the ``if __name__ == "__main__"`` guard so each
snippet ends with a plain ``show(...)``, and emits them as a JS object for the
playground page.
"""

import json
import re
from pathlib import Path

SRC = Path(
    "/Users/clementjambou/src/cadbuildr/monorepo/tsjs/packages/others/data/src/foundation_ex"
)
OUT = Path(__file__).parent / "examples.js"

# (key, label, relative path, note)
EXAMPLES = [
    ("cube", "cube", "parts/cube.py", "extrusion basics"),
    ("donut", "donut", "parts/donut.py", "lathe / revolve"),
    ("pawn", "chess pawn", "parts/chess_parts/chess_pawn.py", "arcs + lathe"),
    ("boolean", "boolean", "parts/line_extrusion_plane_cube_with_side_cylinders.py", "BSP CSG booleans"),
    ("bracket", "sheet metal", "parts/sheet_metal/sheet_metal_l_bracket.py", "base + edge flange"),
    ("loft", "loft", "parts/loft_basic.py", "section skinning"),
    ("sweep", "sweep", "parts/sweep_spline.py", "profile along a spline"),
    ("star", "star", "parts/gold_star.py", "custom polygon"),
    ("badge", "mountain badge", "parts/mountain_svg.py", "SVG art cut (shapely)"),
]


def unwrap_main(code: str) -> str:
    """Turn the __main__ guard into top-level statements."""
    m = re.search(r'\nif __name__ == "__main__":\n((?:[ \t]+.*\n?)*)', code)
    if not m:
        return code.rstrip() + "\n"
    body = "".join(
        line[4:] if line.startswith("    ") else line
        for line in m.group(1).splitlines(keepends=True)
    )
    code = code[: m.start()] + "\n" + body
    return code.rstrip() + "\n"


def clean(code: str) -> str:
    code = code.replace("# %%\n", "")
    code = unwrap_main(code)
    return code.lstrip("\n")


def main() -> None:
    entries = {}
    for key, label, rel, note in EXAMPLES:
        code = clean((SRC / rel).read_text())
        entries[key] = {"label": label, "note": note, "code": code}
    OUT.write_text(
        "// generated by gen_examples.py — real CADbuildr foundation doc examples\n"
        f"export const EXAMPLES = {json.dumps(entries, indent=1)};\n"
    )
    print(f"wrote {OUT} ({len(entries)} examples)")


if __name__ == "__main__":
    main()
